/*
 * SQE API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LineDataDTO struct for LineDataDTO
type LineDataDTO struct {
	LineId int32 `json:"lineId"`
	LineName string `json:"lineName"`
}

// NewLineDataDTO instantiates a new LineDataDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLineDataDTO(lineId int32, lineName string, ) *LineDataDTO {
	this := LineDataDTO{}
	this.LineId = lineId
	this.LineName = lineName
	return &this
}

// NewLineDataDTOWithDefaults instantiates a new LineDataDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLineDataDTOWithDefaults() *LineDataDTO {
	this := LineDataDTO{}
	return &this
}

// GetLineId returns the LineId field value
func (o *LineDataDTO) GetLineId() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.LineId
}

// GetLineIdOk returns a tuple with the LineId field value
// and a boolean to check if the value has been set.
func (o *LineDataDTO) GetLineIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LineId, true
}

// SetLineId sets field value
func (o *LineDataDTO) SetLineId(v int32) {
	o.LineId = v
}

// GetLineName returns the LineName field value
func (o *LineDataDTO) GetLineName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.LineName
}

// GetLineNameOk returns a tuple with the LineName field value
// and a boolean to check if the value has been set.
func (o *LineDataDTO) GetLineNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LineName, true
}

// SetLineName sets field value
func (o *LineDataDTO) SetLineName(v string) {
	o.LineName = v
}

func (o LineDataDTO) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["lineId"] = o.LineId
	}
	if true {
		toSerialize["lineName"] = o.LineName
	}
	return json.Marshal(toSerialize)
}

type NullableLineDataDTO struct {
	value *LineDataDTO
	isSet bool
}

func (v NullableLineDataDTO) Get() *LineDataDTO {
	return v.value
}

func (v *NullableLineDataDTO) Set(val *LineDataDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableLineDataDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableLineDataDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLineDataDTO(val *LineDataDTO) *NullableLineDataDTO {
	return &NullableLineDataDTO{value: val, isSet: true}
}

func (v NullableLineDataDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLineDataDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


