/*
 * SQE API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// BatchUpdatedArtefactTransformDTO struct for BatchUpdatedArtefactTransformDTO
type BatchUpdatedArtefactTransformDTO struct {
	ArtefactPlacements []UpdatedArtefactPlacementDTO `json:"artefactPlacements"`
}

// NewBatchUpdatedArtefactTransformDTO instantiates a new BatchUpdatedArtefactTransformDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchUpdatedArtefactTransformDTO(artefactPlacements []UpdatedArtefactPlacementDTO, ) *BatchUpdatedArtefactTransformDTO {
	this := BatchUpdatedArtefactTransformDTO{}
	this.ArtefactPlacements = artefactPlacements
	return &this
}

// NewBatchUpdatedArtefactTransformDTOWithDefaults instantiates a new BatchUpdatedArtefactTransformDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchUpdatedArtefactTransformDTOWithDefaults() *BatchUpdatedArtefactTransformDTO {
	this := BatchUpdatedArtefactTransformDTO{}
	return &this
}

// GetArtefactPlacements returns the ArtefactPlacements field value
func (o *BatchUpdatedArtefactTransformDTO) GetArtefactPlacements() []UpdatedArtefactPlacementDTO {
	if o == nil  {
		var ret []UpdatedArtefactPlacementDTO
		return ret
	}

	return o.ArtefactPlacements
}

// GetArtefactPlacementsOk returns a tuple with the ArtefactPlacements field value
// and a boolean to check if the value has been set.
func (o *BatchUpdatedArtefactTransformDTO) GetArtefactPlacementsOk() (*[]UpdatedArtefactPlacementDTO, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ArtefactPlacements, true
}

// SetArtefactPlacements sets field value
func (o *BatchUpdatedArtefactTransformDTO) SetArtefactPlacements(v []UpdatedArtefactPlacementDTO) {
	o.ArtefactPlacements = v
}

func (o BatchUpdatedArtefactTransformDTO) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["artefactPlacements"] = o.ArtefactPlacements
	}
	return json.Marshal(toSerialize)
}

type NullableBatchUpdatedArtefactTransformDTO struct {
	value *BatchUpdatedArtefactTransformDTO
	isSet bool
}

func (v NullableBatchUpdatedArtefactTransformDTO) Get() *BatchUpdatedArtefactTransformDTO {
	return v.value
}

func (v *NullableBatchUpdatedArtefactTransformDTO) Set(val *BatchUpdatedArtefactTransformDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchUpdatedArtefactTransformDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchUpdatedArtefactTransformDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchUpdatedArtefactTransformDTO(val *BatchUpdatedArtefactTransformDTO) *NullableBatchUpdatedArtefactTransformDTO {
	return &NullableBatchUpdatedArtefactTransformDTO{value: val, isSet: true}
}

func (v NullableBatchUpdatedArtefactTransformDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchUpdatedArtefactTransformDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


