/*
 * SQE API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qumranica_api_connector
// CreateArtefactDto struct for CreateArtefactDto
type CreateArtefactDto struct {
	MasterImageId int32 `json:"masterImageId"`
	Mask string `json:"mask"`
	Placement *PlacementDto `json:"placement,omitempty"`
	Name *string `json:"name,omitempty"`
	StatusMessage *string `json:"statusMessage,omitempty"`
}
