/*
 * SQE API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qumranica_api_connector
// EditorDto struct for EditorDto
type EditorDto struct {
	Email string `json:"email"`
	Forename *string `json:"forename,omitempty"`
	Surname *string `json:"surname,omitempty"`
	Organization *string `json:"organization,omitempty"`
}
