/*
 * SQE API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qumranica_api_connector
// ArtefactGroupListDto struct for ArtefactGroupListDto
type ArtefactGroupListDto struct {
	ArtefactGroups []ArtefactGroupDto `json:"artefactGroups"`
}
