/*
 * SQE API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qumranica_api_connector
// ImageStackDto struct for ImageStackDto
type ImageStackDto struct {
	Id *int32 `json:"id,omitempty"`
	Images []ImageDto `json:"images"`
	MasterIndex *int32 `json:"masterIndex,omitempty"`
}
