/*
 * SQE API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ResetLoggedInUserPasswordRequestDTO struct for ResetLoggedInUserPasswordRequestDTO
type ResetLoggedInUserPasswordRequestDTO struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

// NewResetLoggedInUserPasswordRequestDTO instantiates a new ResetLoggedInUserPasswordRequestDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResetLoggedInUserPasswordRequestDTO(oldPassword string, newPassword string, ) *ResetLoggedInUserPasswordRequestDTO {
	this := ResetLoggedInUserPasswordRequestDTO{}
	this.OldPassword = oldPassword
	this.NewPassword = newPassword
	return &this
}

// NewResetLoggedInUserPasswordRequestDTOWithDefaults instantiates a new ResetLoggedInUserPasswordRequestDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResetLoggedInUserPasswordRequestDTOWithDefaults() *ResetLoggedInUserPasswordRequestDTO {
	this := ResetLoggedInUserPasswordRequestDTO{}
	return &this
}

// GetOldPassword returns the OldPassword field value
func (o *ResetLoggedInUserPasswordRequestDTO) GetOldPassword() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.OldPassword
}

// GetOldPasswordOk returns a tuple with the OldPassword field value
// and a boolean to check if the value has been set.
func (o *ResetLoggedInUserPasswordRequestDTO) GetOldPasswordOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.OldPassword, true
}

// SetOldPassword sets field value
func (o *ResetLoggedInUserPasswordRequestDTO) SetOldPassword(v string) {
	o.OldPassword = v
}

// GetNewPassword returns the NewPassword field value
func (o *ResetLoggedInUserPasswordRequestDTO) GetNewPassword() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.NewPassword
}

// GetNewPasswordOk returns a tuple with the NewPassword field value
// and a boolean to check if the value has been set.
func (o *ResetLoggedInUserPasswordRequestDTO) GetNewPasswordOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NewPassword, true
}

// SetNewPassword sets field value
func (o *ResetLoggedInUserPasswordRequestDTO) SetNewPassword(v string) {
	o.NewPassword = v
}

func (o ResetLoggedInUserPasswordRequestDTO) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["oldPassword"] = o.OldPassword
	}
	if true {
		toSerialize["newPassword"] = o.NewPassword
	}
	return json.Marshal(toSerialize)
}

type NullableResetLoggedInUserPasswordRequestDTO struct {
	value *ResetLoggedInUserPasswordRequestDTO
	isSet bool
}

func (v NullableResetLoggedInUserPasswordRequestDTO) Get() *ResetLoggedInUserPasswordRequestDTO {
	return v.value
}

func (v *NullableResetLoggedInUserPasswordRequestDTO) Set(val *ResetLoggedInUserPasswordRequestDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableResetLoggedInUserPasswordRequestDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableResetLoggedInUserPasswordRequestDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResetLoggedInUserPasswordRequestDTO(val *ResetLoggedInUserPasswordRequestDTO) *NullableResetLoggedInUserPasswordRequestDTO {
	return &NullableResetLoggedInUserPasswordRequestDTO{value: val, isSet: true}
}

func (v NullableResetLoggedInUserPasswordRequestDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResetLoggedInUserPasswordRequestDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


