/*
 * SQE API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qumranica_api_connector
import (
	"time"
)
// AdminEditorRequestDto struct for AdminEditorRequestDto
type AdminEditorRequestDto struct {
	EditorName *string `json:"editorName,omitempty"`
	EditorEmail string `json:"editorEmail"`
	EditionId int32 `json:"editionId"`
	EditionName string `json:"editionName"`
	Date time.Time `json:"date"`
	MayLock bool `json:"mayLock"`
	MayRead bool `json:"mayRead"`
	MayWrite bool `json:"mayWrite"`
	IsAdmin bool `json:"isAdmin"`
}
