/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ArtefactDTO from './ArtefactDTO';

/**
 * The ArtefactListDTO model module.
 * @module model/ArtefactListDTO
 * @version v1
 */
class ArtefactListDTO {
    /**
     * Constructs a new <code>ArtefactListDTO</code>.
     * @alias module:model/ArtefactListDTO
     * @param artefacts {Array.<module:model/ArtefactDTO>} 
     */
    constructor(artefacts) { 
        
        ArtefactListDTO.initialize(this, artefacts);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, artefacts) { 
        obj['artefacts'] = artefacts;
    }

    /**
     * Constructs a <code>ArtefactListDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArtefactListDTO} obj Optional instance to populate.
     * @return {module:model/ArtefactListDTO} The populated <code>ArtefactListDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArtefactListDTO();

            if (data.hasOwnProperty('artefacts')) {
                obj['artefacts'] = ApiClient.convertToType(data['artefacts'], [ArtefactDTO]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ArtefactDTO>} artefacts
 */
ArtefactListDTO.prototype['artefacts'] = undefined;






export default ArtefactListDTO;

