/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScriptTextFragmentDTO from './ScriptTextFragmentDTO';

/**
 * The EditionScriptLinesDTO model module.
 * @module model/EditionScriptLinesDTO
 * @version v1
 */
class EditionScriptLinesDTO {
    /**
     * Constructs a new <code>EditionScriptLinesDTO</code>.
     * @alias module:model/EditionScriptLinesDTO
     * @param textFragments {Array.<module:model/ScriptTextFragmentDTO>} 
     */
    constructor(textFragments) { 
        
        EditionScriptLinesDTO.initialize(this, textFragments);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, textFragments) { 
        obj['textFragments'] = textFragments;
    }

    /**
     * Constructs a <code>EditionScriptLinesDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EditionScriptLinesDTO} obj Optional instance to populate.
     * @return {module:model/EditionScriptLinesDTO} The populated <code>EditionScriptLinesDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EditionScriptLinesDTO();

            if (data.hasOwnProperty('textFragments')) {
                obj['textFragments'] = ApiClient.convertToType(data['textFragments'], [ScriptTextFragmentDTO]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ScriptTextFragmentDTO>} textFragments
 */
EditionScriptLinesDTO.prototype['textFragments'] = undefined;






export default EditionScriptLinesDTO;

