/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ImagedObjectDTO from './ImagedObjectDTO';

/**
 * The ImagedObjectListDTO model module.
 * @module model/ImagedObjectListDTO
 * @version v1
 */
class ImagedObjectListDTO {
    /**
     * Constructs a new <code>ImagedObjectListDTO</code>.
     * @alias module:model/ImagedObjectListDTO
     * @param imagedObjects {Array.<module:model/ImagedObjectDTO>} 
     */
    constructor(imagedObjects) { 
        
        ImagedObjectListDTO.initialize(this, imagedObjects);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, imagedObjects) { 
        obj['imagedObjects'] = imagedObjects;
    }

    /**
     * Constructs a <code>ImagedObjectListDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ImagedObjectListDTO} obj Optional instance to populate.
     * @return {module:model/ImagedObjectListDTO} The populated <code>ImagedObjectListDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ImagedObjectListDTO();

            if (data.hasOwnProperty('imagedObjects')) {
                obj['imagedObjects'] = ApiClient.convertToType(data['imagedObjects'], [ImagedObjectDTO]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ImagedObjectDTO>} imagedObjects
 */
ImagedObjectListDTO.prototype['imagedObjects'] = undefined;






export default ImagedObjectListDTO;

