/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InstitutionalImageDTO from './InstitutionalImageDTO';

/**
 * The InstitutionalImageListDTO model module.
 * @module model/InstitutionalImageListDTO
 * @version 0.7.2
 */
class InstitutionalImageListDTO {
    /**
     * Constructs a new <code>InstitutionalImageListDTO</code>.
     * @alias module:model/InstitutionalImageListDTO
     * @param institutionalImages {Array.<module:model/InstitutionalImageDTO>} 
     */
    constructor(institutionalImages) { 
        
        InstitutionalImageListDTO.initialize(this, institutionalImages);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, institutionalImages) { 
        obj['institutionalImages'] = institutionalImages;
    }

    /**
     * Constructs a <code>InstitutionalImageListDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstitutionalImageListDTO} obj Optional instance to populate.
     * @return {module:model/InstitutionalImageListDTO} The populated <code>InstitutionalImageListDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstitutionalImageListDTO();

            if (data.hasOwnProperty('institutionalImages')) {
                obj['institutionalImages'] = ApiClient.convertToType(data['institutionalImages'], [InstitutionalImageDTO]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/InstitutionalImageDTO>} institutionalImages
 */
InstitutionalImageListDTO.prototype['institutionalImages'] = undefined;






export default InstitutionalImageListDTO;

