/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PermissionDTO model module.
 * @module model/PermissionDTO
 * @version 0.7.2
 */
class PermissionDTO {
    /**
     * Constructs a new <code>PermissionDTO</code>.
     * @alias module:model/PermissionDTO
     * @param mayRead {Boolean} 
     * @param mayWrite {Boolean} 
     * @param isAdmin {Boolean} 
     */
    constructor(mayRead, mayWrite, isAdmin) { 
        
        PermissionDTO.initialize(this, mayRead, mayWrite, isAdmin);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mayRead, mayWrite, isAdmin) { 
        obj['mayRead'] = mayRead;
        obj['mayWrite'] = mayWrite;
        obj['isAdmin'] = isAdmin;
    }

    /**
     * Constructs a <code>PermissionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PermissionDTO} obj Optional instance to populate.
     * @return {module:model/PermissionDTO} The populated <code>PermissionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PermissionDTO();

            if (data.hasOwnProperty('mayRead')) {
                obj['mayRead'] = ApiClient.convertToType(data['mayRead'], 'Boolean');
            }
            if (data.hasOwnProperty('mayWrite')) {
                obj['mayWrite'] = ApiClient.convertToType(data['mayWrite'], 'Boolean');
            }
            if (data.hasOwnProperty('isAdmin')) {
                obj['isAdmin'] = ApiClient.convertToType(data['isAdmin'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} mayRead
 */
PermissionDTO.prototype['mayRead'] = undefined;

/**
 * @member {Boolean} mayWrite
 */
PermissionDTO.prototype['mayWrite'] = undefined;

/**
 * @member {Boolean} isAdmin
 */
PermissionDTO.prototype['isAdmin'] = undefined;






export default PermissionDTO;

