/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LineDTO from './LineDTO';

/**
 * The TextFragmentDTO model module.
 * @module model/TextFragmentDTO
 * @version 0.7.0
 */
class TextFragmentDTO {
    /**
     * Constructs a new <code>TextFragmentDTO</code>.
     * @alias module:model/TextFragmentDTO
     * @param textFragmentId {Number} 
     * @param textFragmentName {String} 
     * @param editorId {Number} 
     * @param lines {Array.<module:model/LineDTO>} 
     */
    constructor(textFragmentId, textFragmentName, editorId, lines) { 
        
        TextFragmentDTO.initialize(this, textFragmentId, textFragmentName, editorId, lines);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, textFragmentId, textFragmentName, editorId, lines) { 
        obj['textFragmentId'] = textFragmentId;
        obj['textFragmentName'] = textFragmentName;
        obj['editorId'] = editorId;
        obj['lines'] = lines;
    }

    /**
     * Constructs a <code>TextFragmentDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TextFragmentDTO} obj Optional instance to populate.
     * @return {module:model/TextFragmentDTO} The populated <code>TextFragmentDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TextFragmentDTO();

            if (data.hasOwnProperty('textFragmentId')) {
                obj['textFragmentId'] = ApiClient.convertToType(data['textFragmentId'], 'Number');
            }
            if (data.hasOwnProperty('textFragmentName')) {
                obj['textFragmentName'] = ApiClient.convertToType(data['textFragmentName'], 'String');
            }
            if (data.hasOwnProperty('editorId')) {
                obj['editorId'] = ApiClient.convertToType(data['editorId'], 'Number');
            }
            if (data.hasOwnProperty('lines')) {
                obj['lines'] = ApiClient.convertToType(data['lines'], [LineDTO]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} textFragmentId
 */
TextFragmentDTO.prototype['textFragmentId'] = undefined;

/**
 * @member {String} textFragmentName
 */
TextFragmentDTO.prototype['textFragmentName'] = undefined;

/**
 * @member {Number} editorId
 */
TextFragmentDTO.prototype['editorId'] = undefined;

/**
 * @member {Array.<module:model/LineDTO>} lines
 */
TextFragmentDTO.prototype['lines'] = undefined;






export default TextFragmentDTO;

