# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DetailedUserTokenDTO")

model.instance <- DetailedUserTokenDTO$new()

test_that("token", {
  # tests for the property `token` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`token`, "EXPECTED_RESULT")
})

test_that("forename", {
  # tests for the property `forename` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`forename`, "EXPECTED_RESULT")
})

test_that("surname", {
  # tests for the property `surname` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`surname`, "EXPECTED_RESULT")
})

test_that("organization", {
  # tests for the property `organization` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`organization`, "EXPECTED_RESULT")
})

test_that("activated", {
  # tests for the property `activated` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`activated`, "EXPECTED_RESULT")
})

test_that("userId", {
  # tests for the property `userId` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`userId`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

