# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EditionManuscriptMetricsDTO")

model.instance <- EditionManuscriptMetricsDTO$new()

test_that("ppi", {
  # tests for the property `ppi` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`ppi`, "EXPECTED_RESULT")
})

test_that("editorId", {
  # tests for the property `editorId` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`editorId`, "EXPECTED_RESULT")
})

test_that("width", {
  # tests for the property `width` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`width`, "EXPECTED_RESULT")
})

test_that("height", {
  # tests for the property `height` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`height`, "EXPECTED_RESULT")
})

test_that("xOrigin", {
  # tests for the property `xOrigin` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`xOrigin`, "EXPECTED_RESULT")
})

test_that("yOrigin", {
  # tests for the property `yOrigin` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`yOrigin`, "EXPECTED_RESULT")
})

