# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArtefactGroupListDTO")

model.instance <- ArtefactGroupListDTO$new()

test_that("artefactGroups", {
  # tests for the property `artefactGroups` (array[ArtefactGroupDTO])

  # uncomment below to test the property 
  #expect_equal(model.instance$`artefactGroups`, "EXPECTED_RESULT")
})

