# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UpdateArtefactGroupDTO")

model.instance <- UpdateArtefactGroupDTO$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("artefacts", {
  # tests for the property `artefacts` (array[integer])

  # uncomment below to test the property 
  #expect_equal(model.instance$`artefacts`, "EXPECTED_RESULT")
})

