# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ArtefactTextFragmentMatchDTO")

model.instance <- ArtefactTextFragmentMatchDTO$new()

test_that("suggested", {
  # tests for the property `suggested` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`suggested`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("editorId", {
  # tests for the property `editorId` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`editorId`, "EXPECTED_RESULT")
})

