# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UpdateInterpretationRoiDTOList")

model.instance <- UpdateInterpretationRoiDTOList$new()

test_that("rois", {
  # tests for the property `rois` (array[UpdateInterpretationRoiDTO])

  # uncomment below to test the property 
  #expect_equal(model.instance$`rois`, "EXPECTED_RESULT")
})

