# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SetInterpretationRoiDTO")

model.instance <- SetInterpretationRoiDTO$new()

test_that("artefactId", {
  # tests for the property `artefactId` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`artefactId`, "EXPECTED_RESULT")
})

test_that("signInterpretationId", {
  # tests for the property `signInterpretationId` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`signInterpretationId`, "EXPECTED_RESULT")
})

test_that("shape", {
  # tests for the property `shape` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`shape`, "EXPECTED_RESULT")
})

test_that("translate", {
  # tests for the property `translate` (TranslateDTO)

  # uncomment below to test the property 
  #expect_equal(model.instance$`translate`, "EXPECTED_RESULT")
})

test_that("stanceRotation", {
  # tests for the property `stanceRotation` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`stanceRotation`, "EXPECTED_RESULT")
})

test_that("exceptional", {
  # tests for the property `exceptional` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`exceptional`, "EXPECTED_RESULT")
})

test_that("valuesSet", {
  # tests for the property `valuesSet` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`valuesSet`, "EXPECTED_RESULT")
})

