# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CatalogueMatchInputDTO")

model.instance <- CatalogueMatchInputDTO$new()

test_that("catalogSide", {
  # tests for the property `catalogSide` (SideDesignation)

  # uncomment below to test the property 
  #expect_equal(model.instance$`catalogSide`, "EXPECTED_RESULT")
})

test_that("imagedObjectId", {
  # tests for the property `imagedObjectId` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`imagedObjectId`, "EXPECTED_RESULT")
})

test_that("manuscriptId", {
  # tests for the property `manuscriptId` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`manuscriptId`, "EXPECTED_RESULT")
})

test_that("editionName", {
  # tests for the property `editionName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`editionName`, "EXPECTED_RESULT")
})

test_that("editionVolume", {
  # tests for the property `editionVolume` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`editionVolume`, "EXPECTED_RESULT")
})

test_that("editionLocation1", {
  # tests for the property `editionLocation1` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`editionLocation1`, "EXPECTED_RESULT")
})

test_that("editionLocation2", {
  # tests for the property `editionLocation2` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`editionLocation2`, "EXPECTED_RESULT")
})

test_that("editionSide", {
  # tests for the property `editionSide` (SideDesignation)

  # uncomment below to test the property 
  #expect_equal(model.instance$`editionSide`, "EXPECTED_RESULT")
})

test_that("comment", {
  # tests for the property `comment` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`comment`, "EXPECTED_RESULT")
})

test_that("textFragmentId", {
  # tests for the property `textFragmentId` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`textFragmentId`, "EXPECTED_RESULT")
})

test_that("editionId", {
  # tests for the property `editionId` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`editionId`, "EXPECTED_RESULT")
})

test_that("confirmed", {
  # tests for the property `confirmed` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`confirmed`, "EXPECTED_RESULT")
})

