# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ResetUserPasswordRequestDTO")

model.instance <- ResetUserPasswordRequestDTO$new()

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

