# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateAttributeValueDTO")

model.instance <- CreateAttributeValueDTO$new()

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("cssDirectives", {
  # tests for the property `cssDirectives` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`cssDirectives`, "EXPECTED_RESULT")
})

