# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NewUserRequestDTO")

model.instance <- NewUserRequestDTO$new()

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("password", {
  # tests for the property `password` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`password`, "EXPECTED_RESULT")
})

test_that("organization", {
  # tests for the property `organization` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`organization`, "EXPECTED_RESULT")
})

test_that("forename", {
  # tests for the property `forename` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`forename`, "EXPECTED_RESULT")
})

test_that("surname", {
  # tests for the property `surname` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`surname`, "EXPECTED_RESULT")
})

