/* tslint:disable */
/* eslint-disable */
/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArtefactGroupDTO
 */
export interface ArtefactGroupDTO {
    /**
     * 
     * @type {number}
     * @memberof ArtefactGroupDTO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ArtefactGroupDTO
     */
    name: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ArtefactGroupDTO
     */
    artefacts: Array<number>;
}

export function ArtefactGroupDTOFromJSON(json: any): ArtefactGroupDTO {
    return ArtefactGroupDTOFromJSONTyped(json, false);
}

export function ArtefactGroupDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtefactGroupDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'artefacts': json['artefacts'],
    };
}

export function ArtefactGroupDTOToJSON(value?: ArtefactGroupDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'artefacts': value.artefacts,
    };
}


