/* tslint:disable */
/* eslint-disable */
/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InterpretationRoiDTO,
    InterpretationRoiDTOFromJSON,
    InterpretationRoiDTOFromJSONTyped,
    InterpretationRoiDTOToJSON,
    UpdatedInterpretationRoiDTO,
    UpdatedInterpretationRoiDTOFromJSON,
    UpdatedInterpretationRoiDTOFromJSONTyped,
    UpdatedInterpretationRoiDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface BatchEditRoiResponseDTO
 */
export interface BatchEditRoiResponseDTO {
    /**
     * 
     * @type {Array<InterpretationRoiDTO>}
     * @memberof BatchEditRoiResponseDTO
     */
    createRois: Array<InterpretationRoiDTO>;
    /**
     * 
     * @type {Array<UpdatedInterpretationRoiDTO>}
     * @memberof BatchEditRoiResponseDTO
     */
    updateRois: Array<UpdatedInterpretationRoiDTO>;
    /**
     * 
     * @type {Array<number>}
     * @memberof BatchEditRoiResponseDTO
     */
    deleteRois: Array<number>;
}

export function BatchEditRoiResponseDTOFromJSON(json: any): BatchEditRoiResponseDTO {
    return BatchEditRoiResponseDTOFromJSONTyped(json, false);
}

export function BatchEditRoiResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchEditRoiResponseDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createRois': ((json['createRois'] as Array<any>).map(InterpretationRoiDTOFromJSON)),
        'updateRois': ((json['updateRois'] as Array<any>).map(UpdatedInterpretationRoiDTOFromJSON)),
        'deleteRois': json['deleteRois'],
    };
}

export function BatchEditRoiResponseDTOToJSON(value?: BatchEditRoiResponseDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createRois': ((value.createRois as Array<any>).map(InterpretationRoiDTOToJSON)),
        'updateRois': ((value.updateRois as Array<any>).map(UpdatedInterpretationRoiDTOToJSON)),
        'deleteRois': value.deleteRois,
    };
}


