/* tslint:disable */
/* eslint-disable */
/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditorDTO
 */
export interface EditorDTO {
    /**
     * 
     * @type {string}
     * @memberof EditorDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof EditorDTO
     */
    forename?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditorDTO
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditorDTO
     */
    organization?: string | null;
}

export function EditorDTOFromJSON(json: any): EditorDTO {
    return EditorDTOFromJSONTyped(json, false);
}

export function EditorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditorDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'forename': !exists(json, 'forename') ? undefined : json['forename'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'organization': !exists(json, 'organization') ? undefined : json['organization'],
    };
}

export function EditorDTOToJSON(value?: EditorDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'forename': value.forename,
        'surname': value.surname,
        'organization': value.organization,
    };
}


