/* tslint:disable */
/* eslint-disable */
/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstitutionalImageDTO
 */
export interface InstitutionalImageDTO {
    /**
     * 
     * @type {string}
     * @memberof InstitutionalImageDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InstitutionalImageDTO
     */
    thumbnailUrl: string;
    /**
     * 
     * @type {string}
     * @memberof InstitutionalImageDTO
     */
    license: string;
}

export function InstitutionalImageDTOFromJSON(json: any): InstitutionalImageDTO {
    return InstitutionalImageDTOFromJSONTyped(json, false);
}

export function InstitutionalImageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstitutionalImageDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'thumbnailUrl': json['thumbnailUrl'],
        'license': json['license'],
    };
}

export function InstitutionalImageDTOToJSON(value?: InstitutionalImageDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'thumbnailUrl': value.thumbnailUrl,
        'license': value.license,
    };
}


