/* tslint:disable */
/* eslint-disable */
/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InterpretationRoiDTO,
    InterpretationRoiDTOFromJSON,
    InterpretationRoiDTOFromJSONTyped,
    InterpretationRoiDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface InterpretationRoiDTOList
 */
export interface InterpretationRoiDTOList {
    /**
     * 
     * @type {Array<InterpretationRoiDTO>}
     * @memberof InterpretationRoiDTOList
     */
    rois: Array<InterpretationRoiDTO>;
}

export function InterpretationRoiDTOListFromJSON(json: any): InterpretationRoiDTOList {
    return InterpretationRoiDTOListFromJSONTyped(json, false);
}

export function InterpretationRoiDTOListFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterpretationRoiDTOList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rois': ((json['rois'] as Array<any>).map(InterpretationRoiDTOFromJSON)),
    };
}

export function InterpretationRoiDTOListToJSON(value?: InterpretationRoiDTOList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rois': ((value.rois as Array<any>).map(InterpretationRoiDTOToJSON)),
    };
}


