/* tslint:disable */
/* eslint-disable */
/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CommentaryDTO,
    CommentaryDTOFromJSON,
    CommentaryDTOFromJSONTyped,
    CommentaryDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface InterpretationAttributeDTO
 */
export interface InterpretationAttributeDTO {
    /**
     * 
     * @type {number}
     * @memberof InterpretationAttributeDTO
     */
    interpretationAttributeId: number;
    /**
     * 
     * @type {string}
     * @memberof InterpretationAttributeDTO
     */
    attributeString: string;
    /**
     * 
     * @type {string}
     * @memberof InterpretationAttributeDTO
     */
    attributeValueString: string;
    /**
     * 
     * @type {number}
     * @memberof InterpretationAttributeDTO
     */
    creatorId: number;
    /**
     * 
     * @type {number}
     * @memberof InterpretationAttributeDTO
     */
    editorId: number;
    /**
     * 
     * @type {CommentaryDTO}
     * @memberof InterpretationAttributeDTO
     */
    commentary?: CommentaryDTO | null;
    /**
     * 
     * @type {number}
     * @memberof InterpretationAttributeDTO
     */
    sequence?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InterpretationAttributeDTO
     */
    attributeId: number;
    /**
     * 
     * @type {number}
     * @memberof InterpretationAttributeDTO
     */
    attributeValueId: number;
}

export function InterpretationAttributeDTOFromJSON(json: any): InterpretationAttributeDTO {
    return InterpretationAttributeDTOFromJSONTyped(json, false);
}

export function InterpretationAttributeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterpretationAttributeDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'interpretationAttributeId': json['interpretationAttributeId'],
        'attributeString': json['attributeString'],
        'attributeValueString': json['attributeValueString'],
        'creatorId': json['creatorId'],
        'editorId': json['editorId'],
        'commentary': !exists(json, 'commentary') ? undefined : CommentaryDTOFromJSON(json['commentary']),
        'sequence': !exists(json, 'sequence') ? undefined : json['sequence'],
        'attributeId': json['attributeId'],
        'attributeValueId': json['attributeValueId'],
    };
}

export function InterpretationAttributeDTOToJSON(value?: InterpretationAttributeDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'interpretationAttributeId': value.interpretationAttributeId,
        'attributeString': value.attributeString,
        'attributeValueString': value.attributeValueString,
        'creatorId': value.creatorId,
        'editorId': value.editorId,
        'commentary': CommentaryDTOToJSON(value.commentary),
        'sequence': value.sequence,
        'attributeId': value.attributeId,
        'attributeValueId': value.attributeValueId,
    };
}


