/* tslint:disable */
/* eslint-disable */
/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SignDTO,
    SignDTOFromJSON,
    SignDTOFromJSONTyped,
    SignDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface LineDTO
 */
export interface LineDTO {
    /**
     * 
     * @type {number}
     * @memberof LineDTO
     */
    lineId: number;
    /**
     * 
     * @type {string}
     * @memberof LineDTO
     */
    lineName: string;
    /**
     * 
     * @type {number}
     * @memberof LineDTO
     */
    editorId: number;
    /**
     * 
     * @type {Array<SignDTO>}
     * @memberof LineDTO
     */
    signs: Array<SignDTO>;
}

export function LineDTOFromJSON(json: any): LineDTO {
    return LineDTOFromJSONTyped(json, false);
}

export function LineDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lineId': json['lineId'],
        'lineName': json['lineName'],
        'editorId': json['editorId'],
        'signs': ((json['signs'] as Array<any>).map(SignDTOFromJSON)),
    };
}

export function LineDTOToJSON(value?: LineDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lineId': value.lineId,
        'lineName': value.lineName,
        'editorId': value.editorId,
        'signs': ((value.signs as Array<any>).map(SignDTOToJSON)),
    };
}


