/* tslint:disable */
/* eslint-disable */
/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetForgottenUserPasswordRequestDTO
 */
export interface ResetForgottenUserPasswordRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof ResetForgottenUserPasswordRequestDTO
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ResetForgottenUserPasswordRequestDTO
     */
    token: string;
}

export function ResetForgottenUserPasswordRequestDTOFromJSON(json: any): ResetForgottenUserPasswordRequestDTO {
    return ResetForgottenUserPasswordRequestDTOFromJSONTyped(json, false);
}

export function ResetForgottenUserPasswordRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetForgottenUserPasswordRequestDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': json['password'],
        'token': json['token'],
    };
}

export function ResetForgottenUserPasswordRequestDTOToJSON(value?: ResetForgottenUserPasswordRequestDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'token': value.token,
    };
}


