/* tslint:disable */
/* eslint-disable */
/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetUserPasswordRequestDTO
 */
export interface ResetUserPasswordRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof ResetUserPasswordRequestDTO
     */
    email: string;
}

export function ResetUserPasswordRequestDTOFromJSON(json: any): ResetUserPasswordRequestDTO {
    return ResetUserPasswordRequestDTOFromJSONTyped(json, false);
}

export function ResetUserPasswordRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetUserPasswordRequestDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ResetUserPasswordRequestDTOToJSON(value?: ResetUserPasswordRequestDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}


