/* tslint:disable */
/* eslint-disable */
/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PlacementDTO,
    PlacementDTOFromJSON,
    PlacementDTOFromJSONTyped,
    PlacementDTOToJSON,
    SignInterpretationDTO,
    SignInterpretationDTOFromJSON,
    SignInterpretationDTOFromJSONTyped,
    SignInterpretationDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface ScriptArtefactCharactersDTO
 */
export interface ScriptArtefactCharactersDTO {
    /**
     * 
     * @type {string}
     * @memberof ScriptArtefactCharactersDTO
     */
    artefactName: string;
    /**
     * 
     * @type {number}
     * @memberof ScriptArtefactCharactersDTO
     */
    artefactId: number;
    /**
     * 
     * @type {PlacementDTO}
     * @memberof ScriptArtefactCharactersDTO
     */
    placement: PlacementDTO;
    /**
     * 
     * @type {Array<SignInterpretationDTO>}
     * @memberof ScriptArtefactCharactersDTO
     */
    characters: Array<SignInterpretationDTO>;
}

export function ScriptArtefactCharactersDTOFromJSON(json: any): ScriptArtefactCharactersDTO {
    return ScriptArtefactCharactersDTOFromJSONTyped(json, false);
}

export function ScriptArtefactCharactersDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScriptArtefactCharactersDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'artefactName': json['artefactName'],
        'artefactId': json['artefactId'],
        'placement': PlacementDTOFromJSON(json['placement']),
        'characters': ((json['characters'] as Array<any>).map(SignInterpretationDTOFromJSON)),
    };
}

export function ScriptArtefactCharactersDTOToJSON(value?: ScriptArtefactCharactersDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'artefactName': value.artefactName,
        'artefactId': value.artefactId,
        'placement': PlacementDTOToJSON(value.placement),
        'characters': ((value.characters as Array<any>).map(SignInterpretationDTOToJSON)),
    };
}


