/* tslint:disable */
/* eslint-disable */
/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SetInterpretationRoiDTO,
    SetInterpretationRoiDTOFromJSON,
    SetInterpretationRoiDTOFromJSONTyped,
    SetInterpretationRoiDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface SetInterpretationRoiDTOList
 */
export interface SetInterpretationRoiDTOList {
    /**
     * 
     * @type {Array<SetInterpretationRoiDTO>}
     * @memberof SetInterpretationRoiDTOList
     */
    rois: Array<SetInterpretationRoiDTO>;
}

export function SetInterpretationRoiDTOListFromJSON(json: any): SetInterpretationRoiDTOList {
    return SetInterpretationRoiDTOListFromJSONTyped(json, false);
}

export function SetInterpretationRoiDTOListFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetInterpretationRoiDTOList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rois': ((json['rois'] as Array<any>).map(SetInterpretationRoiDTOFromJSON)),
    };
}

export function SetInterpretationRoiDTOListToJSON(value?: SetInterpretationRoiDTOList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rois': ((value.rois as Array<any>).map(SetInterpretationRoiDTOToJSON)),
    };
}


