# SQE API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CatalogueMatchDTO
#' @description CatalogueMatchDTO Class
#' @format An \code{R6Class} generator object
#' @field imageCatalogId  integer 
#'
#' @field institution  character 
#'
#' @field catalogueNumber1  character 
#'
#' @field catalogueNumber2  character [optional]
#'
#' @field proxy  character [optional]
#'
#' @field url  character 
#'
#' @field filename  character 
#'
#' @field suffix  character 
#'
#' @field thumbnail  character 
#'
#' @field license  character 
#'
#' @field iaaEditionCatalogueId  integer 
#'
#' @field manuscriptName  character 
#'
#' @field name  character 
#'
#' @field matchAuthor  character 
#'
#' @field matchConfirmationAuthor  character [optional]
#'
#' @field matchId  integer 
#'
#' @field dateOfMatch  character 
#'
#' @field dateOfConfirmation  character [optional]
#'
#' @field catalogSide  \link{SideDesignation} [optional]
#'
#' @field imagedObjectId  character 
#'
#' @field manuscriptId  integer 
#'
#' @field editionName  character 
#'
#' @field editionVolume  character 
#'
#' @field editionLocation1  character 
#'
#' @field editionLocation2  character 
#'
#' @field editionSide  \link{SideDesignation} 
#'
#' @field comment  character [optional]
#'
#' @field textFragmentId  integer 
#'
#' @field editionId  integer 
#'
#' @field confirmed  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CatalogueMatchDTO <- R6::R6Class(
  'CatalogueMatchDTO',
  public = list(
    `imageCatalogId` = NULL,
    `institution` = NULL,
    `catalogueNumber1` = NULL,
    `catalogueNumber2` = NULL,
    `proxy` = NULL,
    `url` = NULL,
    `filename` = NULL,
    `suffix` = NULL,
    `thumbnail` = NULL,
    `license` = NULL,
    `iaaEditionCatalogueId` = NULL,
    `manuscriptName` = NULL,
    `name` = NULL,
    `matchAuthor` = NULL,
    `matchConfirmationAuthor` = NULL,
    `matchId` = NULL,
    `dateOfMatch` = NULL,
    `dateOfConfirmation` = NULL,
    `catalogSide` = NULL,
    `imagedObjectId` = NULL,
    `manuscriptId` = NULL,
    `editionName` = NULL,
    `editionVolume` = NULL,
    `editionLocation1` = NULL,
    `editionLocation2` = NULL,
    `editionSide` = NULL,
    `comment` = NULL,
    `textFragmentId` = NULL,
    `editionId` = NULL,
    `confirmed` = NULL,
    initialize = function(`imageCatalogId`, `institution`, `catalogueNumber1`, `url`, `filename`, `suffix`, `thumbnail`, `license`, `iaaEditionCatalogueId`, `manuscriptName`, `name`, `matchAuthor`, `matchId`, `dateOfMatch`, `imagedObjectId`, `manuscriptId`, `editionName`, `editionVolume`, `editionLocation1`, `editionLocation2`, `editionSide`, `textFragmentId`, `editionId`, `catalogueNumber2`=NULL, `proxy`=NULL, `matchConfirmationAuthor`=NULL, `dateOfConfirmation`=NULL, `catalogSide`=NULL, `comment`=NULL, `confirmed`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`imageCatalogId`)) {
        stopifnot(is.numeric(`imageCatalogId`), length(`imageCatalogId`) == 1)
        self$`imageCatalogId` <- `imageCatalogId`
      }
      if (!missing(`institution`)) {
        stopifnot(is.character(`institution`), length(`institution`) == 1)
        self$`institution` <- `institution`
      }
      if (!missing(`catalogueNumber1`)) {
        stopifnot(is.character(`catalogueNumber1`), length(`catalogueNumber1`) == 1)
        self$`catalogueNumber1` <- `catalogueNumber1`
      }
      if (!missing(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
        self$`url` <- `url`
      }
      if (!missing(`filename`)) {
        stopifnot(is.character(`filename`), length(`filename`) == 1)
        self$`filename` <- `filename`
      }
      if (!missing(`suffix`)) {
        stopifnot(is.character(`suffix`), length(`suffix`) == 1)
        self$`suffix` <- `suffix`
      }
      if (!missing(`thumbnail`)) {
        stopifnot(is.character(`thumbnail`), length(`thumbnail`) == 1)
        self$`thumbnail` <- `thumbnail`
      }
      if (!missing(`license`)) {
        stopifnot(is.character(`license`), length(`license`) == 1)
        self$`license` <- `license`
      }
      if (!missing(`iaaEditionCatalogueId`)) {
        stopifnot(is.numeric(`iaaEditionCatalogueId`), length(`iaaEditionCatalogueId`) == 1)
        self$`iaaEditionCatalogueId` <- `iaaEditionCatalogueId`
      }
      if (!missing(`manuscriptName`)) {
        stopifnot(is.character(`manuscriptName`), length(`manuscriptName`) == 1)
        self$`manuscriptName` <- `manuscriptName`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`matchAuthor`)) {
        stopifnot(is.character(`matchAuthor`), length(`matchAuthor`) == 1)
        self$`matchAuthor` <- `matchAuthor`
      }
      if (!missing(`matchId`)) {
        stopifnot(is.numeric(`matchId`), length(`matchId`) == 1)
        self$`matchId` <- `matchId`
      }
      if (!missing(`dateOfMatch`)) {
        stopifnot(is.character(`dateOfMatch`), length(`dateOfMatch`) == 1)
        self$`dateOfMatch` <- `dateOfMatch`
      }
      if (!missing(`imagedObjectId`)) {
        stopifnot(is.character(`imagedObjectId`), length(`imagedObjectId`) == 1)
        self$`imagedObjectId` <- `imagedObjectId`
      }
      if (!missing(`manuscriptId`)) {
        stopifnot(is.numeric(`manuscriptId`), length(`manuscriptId`) == 1)
        self$`manuscriptId` <- `manuscriptId`
      }
      if (!missing(`editionName`)) {
        stopifnot(is.character(`editionName`), length(`editionName`) == 1)
        self$`editionName` <- `editionName`
      }
      if (!missing(`editionVolume`)) {
        stopifnot(is.character(`editionVolume`), length(`editionVolume`) == 1)
        self$`editionVolume` <- `editionVolume`
      }
      if (!missing(`editionLocation1`)) {
        stopifnot(is.character(`editionLocation1`), length(`editionLocation1`) == 1)
        self$`editionLocation1` <- `editionLocation1`
      }
      if (!missing(`editionLocation2`)) {
        stopifnot(is.character(`editionLocation2`), length(`editionLocation2`) == 1)
        self$`editionLocation2` <- `editionLocation2`
      }
      if (!missing(`editionSide`)) {
        stopifnot(R6::is.R6(`editionSide`))
        self$`editionSide` <- `editionSide`
      }
      if (!missing(`textFragmentId`)) {
        stopifnot(is.numeric(`textFragmentId`), length(`textFragmentId`) == 1)
        self$`textFragmentId` <- `textFragmentId`
      }
      if (!missing(`editionId`)) {
        stopifnot(is.numeric(`editionId`), length(`editionId`) == 1)
        self$`editionId` <- `editionId`
      }
      if (!is.null(`catalogueNumber2`)) {
        stopifnot(is.character(`catalogueNumber2`), length(`catalogueNumber2`) == 1)
        self$`catalogueNumber2` <- `catalogueNumber2`
      }
      if (!is.null(`proxy`)) {
        stopifnot(is.character(`proxy`), length(`proxy`) == 1)
        self$`proxy` <- `proxy`
      }
      if (!is.null(`matchConfirmationAuthor`)) {
        stopifnot(is.character(`matchConfirmationAuthor`), length(`matchConfirmationAuthor`) == 1)
        self$`matchConfirmationAuthor` <- `matchConfirmationAuthor`
      }
      if (!is.null(`dateOfConfirmation`)) {
        stopifnot(is.character(`dateOfConfirmation`), length(`dateOfConfirmation`) == 1)
        self$`dateOfConfirmation` <- `dateOfConfirmation`
      }
      if (!is.null(`catalogSide`)) {
        stopifnot(R6::is.R6(`catalogSide`))
        self$`catalogSide` <- `catalogSide`
      }
      if (!is.null(`comment`)) {
        stopifnot(is.character(`comment`), length(`comment`) == 1)
        self$`comment` <- `comment`
      }
      if (!is.null(`confirmed`)) {
        self$`confirmed` <- `confirmed`
      }
    },
    toJSON = function() {
      CatalogueMatchDTOObject <- list()
      if (!is.null(self$`imageCatalogId`)) {
        CatalogueMatchDTOObject[['imageCatalogId']] <-
          self$`imageCatalogId`
      }
      if (!is.null(self$`institution`)) {
        CatalogueMatchDTOObject[['institution']] <-
          self$`institution`
      }
      if (!is.null(self$`catalogueNumber1`)) {
        CatalogueMatchDTOObject[['catalogueNumber1']] <-
          self$`catalogueNumber1`
      }
      if (!is.null(self$`catalogueNumber2`)) {
        CatalogueMatchDTOObject[['catalogueNumber2']] <-
          self$`catalogueNumber2`
      }
      if (!is.null(self$`proxy`)) {
        CatalogueMatchDTOObject[['proxy']] <-
          self$`proxy`
      }
      if (!is.null(self$`url`)) {
        CatalogueMatchDTOObject[['url']] <-
          self$`url`
      }
      if (!is.null(self$`filename`)) {
        CatalogueMatchDTOObject[['filename']] <-
          self$`filename`
      }
      if (!is.null(self$`suffix`)) {
        CatalogueMatchDTOObject[['suffix']] <-
          self$`suffix`
      }
      if (!is.null(self$`thumbnail`)) {
        CatalogueMatchDTOObject[['thumbnail']] <-
          self$`thumbnail`
      }
      if (!is.null(self$`license`)) {
        CatalogueMatchDTOObject[['license']] <-
          self$`license`
      }
      if (!is.null(self$`iaaEditionCatalogueId`)) {
        CatalogueMatchDTOObject[['iaaEditionCatalogueId']] <-
          self$`iaaEditionCatalogueId`
      }
      if (!is.null(self$`manuscriptName`)) {
        CatalogueMatchDTOObject[['manuscriptName']] <-
          self$`manuscriptName`
      }
      if (!is.null(self$`name`)) {
        CatalogueMatchDTOObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`matchAuthor`)) {
        CatalogueMatchDTOObject[['matchAuthor']] <-
          self$`matchAuthor`
      }
      if (!is.null(self$`matchConfirmationAuthor`)) {
        CatalogueMatchDTOObject[['matchConfirmationAuthor']] <-
          self$`matchConfirmationAuthor`
      }
      if (!is.null(self$`matchId`)) {
        CatalogueMatchDTOObject[['matchId']] <-
          self$`matchId`
      }
      if (!is.null(self$`dateOfMatch`)) {
        CatalogueMatchDTOObject[['dateOfMatch']] <-
          self$`dateOfMatch`
      }
      if (!is.null(self$`dateOfConfirmation`)) {
        CatalogueMatchDTOObject[['dateOfConfirmation']] <-
          self$`dateOfConfirmation`
      }
      if (!is.null(self$`catalogSide`)) {
        CatalogueMatchDTOObject[['catalogSide']] <-
          self$`catalogSide`$toJSON()
      }
      if (!is.null(self$`imagedObjectId`)) {
        CatalogueMatchDTOObject[['imagedObjectId']] <-
          self$`imagedObjectId`
      }
      if (!is.null(self$`manuscriptId`)) {
        CatalogueMatchDTOObject[['manuscriptId']] <-
          self$`manuscriptId`
      }
      if (!is.null(self$`editionName`)) {
        CatalogueMatchDTOObject[['editionName']] <-
          self$`editionName`
      }
      if (!is.null(self$`editionVolume`)) {
        CatalogueMatchDTOObject[['editionVolume']] <-
          self$`editionVolume`
      }
      if (!is.null(self$`editionLocation1`)) {
        CatalogueMatchDTOObject[['editionLocation1']] <-
          self$`editionLocation1`
      }
      if (!is.null(self$`editionLocation2`)) {
        CatalogueMatchDTOObject[['editionLocation2']] <-
          self$`editionLocation2`
      }
      if (!is.null(self$`editionSide`)) {
        CatalogueMatchDTOObject[['editionSide']] <-
          self$`editionSide`$toJSON()
      }
      if (!is.null(self$`comment`)) {
        CatalogueMatchDTOObject[['comment']] <-
          self$`comment`
      }
      if (!is.null(self$`textFragmentId`)) {
        CatalogueMatchDTOObject[['textFragmentId']] <-
          self$`textFragmentId`
      }
      if (!is.null(self$`editionId`)) {
        CatalogueMatchDTOObject[['editionId']] <-
          self$`editionId`
      }
      if (!is.null(self$`confirmed`)) {
        CatalogueMatchDTOObject[['confirmed']] <-
          self$`confirmed`
      }

      CatalogueMatchDTOObject
    },
    fromJSON = function(CatalogueMatchDTOJson) {
      CatalogueMatchDTOObject <- jsonlite::fromJSON(CatalogueMatchDTOJson)
      if (!is.null(CatalogueMatchDTOObject$`imageCatalogId`)) {
        self$`imageCatalogId` <- CatalogueMatchDTOObject$`imageCatalogId`
      }
      if (!is.null(CatalogueMatchDTOObject$`institution`)) {
        self$`institution` <- CatalogueMatchDTOObject$`institution`
      }
      if (!is.null(CatalogueMatchDTOObject$`catalogueNumber1`)) {
        self$`catalogueNumber1` <- CatalogueMatchDTOObject$`catalogueNumber1`
      }
      if (!is.null(CatalogueMatchDTOObject$`catalogueNumber2`)) {
        self$`catalogueNumber2` <- CatalogueMatchDTOObject$`catalogueNumber2`
      }
      if (!is.null(CatalogueMatchDTOObject$`proxy`)) {
        self$`proxy` <- CatalogueMatchDTOObject$`proxy`
      }
      if (!is.null(CatalogueMatchDTOObject$`url`)) {
        self$`url` <- CatalogueMatchDTOObject$`url`
      }
      if (!is.null(CatalogueMatchDTOObject$`filename`)) {
        self$`filename` <- CatalogueMatchDTOObject$`filename`
      }
      if (!is.null(CatalogueMatchDTOObject$`suffix`)) {
        self$`suffix` <- CatalogueMatchDTOObject$`suffix`
      }
      if (!is.null(CatalogueMatchDTOObject$`thumbnail`)) {
        self$`thumbnail` <- CatalogueMatchDTOObject$`thumbnail`
      }
      if (!is.null(CatalogueMatchDTOObject$`license`)) {
        self$`license` <- CatalogueMatchDTOObject$`license`
      }
      if (!is.null(CatalogueMatchDTOObject$`iaaEditionCatalogueId`)) {
        self$`iaaEditionCatalogueId` <- CatalogueMatchDTOObject$`iaaEditionCatalogueId`
      }
      if (!is.null(CatalogueMatchDTOObject$`manuscriptName`)) {
        self$`manuscriptName` <- CatalogueMatchDTOObject$`manuscriptName`
      }
      if (!is.null(CatalogueMatchDTOObject$`name`)) {
        self$`name` <- CatalogueMatchDTOObject$`name`
      }
      if (!is.null(CatalogueMatchDTOObject$`matchAuthor`)) {
        self$`matchAuthor` <- CatalogueMatchDTOObject$`matchAuthor`
      }
      if (!is.null(CatalogueMatchDTOObject$`matchConfirmationAuthor`)) {
        self$`matchConfirmationAuthor` <- CatalogueMatchDTOObject$`matchConfirmationAuthor`
      }
      if (!is.null(CatalogueMatchDTOObject$`matchId`)) {
        self$`matchId` <- CatalogueMatchDTOObject$`matchId`
      }
      if (!is.null(CatalogueMatchDTOObject$`dateOfMatch`)) {
        self$`dateOfMatch` <- CatalogueMatchDTOObject$`dateOfMatch`
      }
      if (!is.null(CatalogueMatchDTOObject$`dateOfConfirmation`)) {
        self$`dateOfConfirmation` <- CatalogueMatchDTOObject$`dateOfConfirmation`
      }
      if (!is.null(CatalogueMatchDTOObject$`catalogSide`)) {
        catalogSideObject <- SideDesignation$new()
        catalogSideObject$fromJSON(jsonlite::toJSON(CatalogueMatchDTOObject$catalogSide, auto_unbox = TRUE, digits = NA))
        self$`catalogSide` <- catalogSideObject
      }
      if (!is.null(CatalogueMatchDTOObject$`imagedObjectId`)) {
        self$`imagedObjectId` <- CatalogueMatchDTOObject$`imagedObjectId`
      }
      if (!is.null(CatalogueMatchDTOObject$`manuscriptId`)) {
        self$`manuscriptId` <- CatalogueMatchDTOObject$`manuscriptId`
      }
      if (!is.null(CatalogueMatchDTOObject$`editionName`)) {
        self$`editionName` <- CatalogueMatchDTOObject$`editionName`
      }
      if (!is.null(CatalogueMatchDTOObject$`editionVolume`)) {
        self$`editionVolume` <- CatalogueMatchDTOObject$`editionVolume`
      }
      if (!is.null(CatalogueMatchDTOObject$`editionLocation1`)) {
        self$`editionLocation1` <- CatalogueMatchDTOObject$`editionLocation1`
      }
      if (!is.null(CatalogueMatchDTOObject$`editionLocation2`)) {
        self$`editionLocation2` <- CatalogueMatchDTOObject$`editionLocation2`
      }
      if (!is.null(CatalogueMatchDTOObject$`editionSide`)) {
        editionSideObject <- SideDesignation$new()
        editionSideObject$fromJSON(jsonlite::toJSON(CatalogueMatchDTOObject$editionSide, auto_unbox = TRUE, digits = NA))
        self$`editionSide` <- editionSideObject
      }
      if (!is.null(CatalogueMatchDTOObject$`comment`)) {
        self$`comment` <- CatalogueMatchDTOObject$`comment`
      }
      if (!is.null(CatalogueMatchDTOObject$`textFragmentId`)) {
        self$`textFragmentId` <- CatalogueMatchDTOObject$`textFragmentId`
      }
      if (!is.null(CatalogueMatchDTOObject$`editionId`)) {
        self$`editionId` <- CatalogueMatchDTOObject$`editionId`
      }
      if (!is.null(CatalogueMatchDTOObject$`confirmed`)) {
        self$`confirmed` <- CatalogueMatchDTOObject$`confirmed`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`imageCatalogId`)) {
        sprintf(
        '"imageCatalogId":
          %d
                ',
        self$`imageCatalogId`
        )},
        if (!is.null(self$`institution`)) {
        sprintf(
        '"institution":
          "%s"
                ',
        self$`institution`
        )},
        if (!is.null(self$`catalogueNumber1`)) {
        sprintf(
        '"catalogueNumber1":
          "%s"
                ',
        self$`catalogueNumber1`
        )},
        if (!is.null(self$`catalogueNumber2`)) {
        sprintf(
        '"catalogueNumber2":
          "%s"
                ',
        self$`catalogueNumber2`
        )},
        if (!is.null(self$`proxy`)) {
        sprintf(
        '"proxy":
          "%s"
                ',
        self$`proxy`
        )},
        if (!is.null(self$`url`)) {
        sprintf(
        '"url":
          "%s"
                ',
        self$`url`
        )},
        if (!is.null(self$`filename`)) {
        sprintf(
        '"filename":
          "%s"
                ',
        self$`filename`
        )},
        if (!is.null(self$`suffix`)) {
        sprintf(
        '"suffix":
          "%s"
                ',
        self$`suffix`
        )},
        if (!is.null(self$`thumbnail`)) {
        sprintf(
        '"thumbnail":
          "%s"
                ',
        self$`thumbnail`
        )},
        if (!is.null(self$`license`)) {
        sprintf(
        '"license":
          "%s"
                ',
        self$`license`
        )},
        if (!is.null(self$`iaaEditionCatalogueId`)) {
        sprintf(
        '"iaaEditionCatalogueId":
          %d
                ',
        self$`iaaEditionCatalogueId`
        )},
        if (!is.null(self$`manuscriptName`)) {
        sprintf(
        '"manuscriptName":
          "%s"
                ',
        self$`manuscriptName`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`matchAuthor`)) {
        sprintf(
        '"matchAuthor":
          "%s"
                ',
        self$`matchAuthor`
        )},
        if (!is.null(self$`matchConfirmationAuthor`)) {
        sprintf(
        '"matchConfirmationAuthor":
          "%s"
                ',
        self$`matchConfirmationAuthor`
        )},
        if (!is.null(self$`matchId`)) {
        sprintf(
        '"matchId":
          %d
                ',
        self$`matchId`
        )},
        if (!is.null(self$`dateOfMatch`)) {
        sprintf(
        '"dateOfMatch":
          "%s"
                ',
        self$`dateOfMatch`
        )},
        if (!is.null(self$`dateOfConfirmation`)) {
        sprintf(
        '"dateOfConfirmation":
          "%s"
                ',
        self$`dateOfConfirmation`
        )},
        if (!is.null(self$`catalogSide`)) {
        sprintf(
        '"catalogSide":
        %s
        ',
        jsonlite::toJSON(self$`catalogSide`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`imagedObjectId`)) {
        sprintf(
        '"imagedObjectId":
          "%s"
                ',
        self$`imagedObjectId`
        )},
        if (!is.null(self$`manuscriptId`)) {
        sprintf(
        '"manuscriptId":
          %d
                ',
        self$`manuscriptId`
        )},
        if (!is.null(self$`editionName`)) {
        sprintf(
        '"editionName":
          "%s"
                ',
        self$`editionName`
        )},
        if (!is.null(self$`editionVolume`)) {
        sprintf(
        '"editionVolume":
          "%s"
                ',
        self$`editionVolume`
        )},
        if (!is.null(self$`editionLocation1`)) {
        sprintf(
        '"editionLocation1":
          "%s"
                ',
        self$`editionLocation1`
        )},
        if (!is.null(self$`editionLocation2`)) {
        sprintf(
        '"editionLocation2":
          "%s"
                ',
        self$`editionLocation2`
        )},
        if (!is.null(self$`editionSide`)) {
        sprintf(
        '"editionSide":
        %s
        ',
        jsonlite::toJSON(self$`editionSide`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`comment`)) {
        sprintf(
        '"comment":
          "%s"
                ',
        self$`comment`
        )},
        if (!is.null(self$`textFragmentId`)) {
        sprintf(
        '"textFragmentId":
          %d
                ',
        self$`textFragmentId`
        )},
        if (!is.null(self$`editionId`)) {
        sprintf(
        '"editionId":
          %d
                ',
        self$`editionId`
        )},
        if (!is.null(self$`confirmed`)) {
        sprintf(
        '"confirmed":
          "%s"
                ',
        self$`confirmed`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CatalogueMatchDTOJson) {
      CatalogueMatchDTOObject <- jsonlite::fromJSON(CatalogueMatchDTOJson)
      self$`imageCatalogId` <- CatalogueMatchDTOObject$`imageCatalogId`
      self$`institution` <- CatalogueMatchDTOObject$`institution`
      self$`catalogueNumber1` <- CatalogueMatchDTOObject$`catalogueNumber1`
      self$`catalogueNumber2` <- CatalogueMatchDTOObject$`catalogueNumber2`
      self$`proxy` <- CatalogueMatchDTOObject$`proxy`
      self$`url` <- CatalogueMatchDTOObject$`url`
      self$`filename` <- CatalogueMatchDTOObject$`filename`
      self$`suffix` <- CatalogueMatchDTOObject$`suffix`
      self$`thumbnail` <- CatalogueMatchDTOObject$`thumbnail`
      self$`license` <- CatalogueMatchDTOObject$`license`
      self$`iaaEditionCatalogueId` <- CatalogueMatchDTOObject$`iaaEditionCatalogueId`
      self$`manuscriptName` <- CatalogueMatchDTOObject$`manuscriptName`
      self$`name` <- CatalogueMatchDTOObject$`name`
      self$`matchAuthor` <- CatalogueMatchDTOObject$`matchAuthor`
      self$`matchConfirmationAuthor` <- CatalogueMatchDTOObject$`matchConfirmationAuthor`
      self$`matchId` <- CatalogueMatchDTOObject$`matchId`
      self$`dateOfMatch` <- CatalogueMatchDTOObject$`dateOfMatch`
      self$`dateOfConfirmation` <- CatalogueMatchDTOObject$`dateOfConfirmation`
      self$`catalogSide` <- SideDesignation$new()$fromJSON(jsonlite::toJSON(CatalogueMatchDTOObject$catalogSide, auto_unbox = TRUE, digits = NA))
      self$`imagedObjectId` <- CatalogueMatchDTOObject$`imagedObjectId`
      self$`manuscriptId` <- CatalogueMatchDTOObject$`manuscriptId`
      self$`editionName` <- CatalogueMatchDTOObject$`editionName`
      self$`editionVolume` <- CatalogueMatchDTOObject$`editionVolume`
      self$`editionLocation1` <- CatalogueMatchDTOObject$`editionLocation1`
      self$`editionLocation2` <- CatalogueMatchDTOObject$`editionLocation2`
      self$`editionSide` <- SideDesignation$new()$fromJSON(jsonlite::toJSON(CatalogueMatchDTOObject$editionSide, auto_unbox = TRUE, digits = NA))
      self$`comment` <- CatalogueMatchDTOObject$`comment`
      self$`textFragmentId` <- CatalogueMatchDTOObject$`textFragmentId`
      self$`editionId` <- CatalogueMatchDTOObject$`editionId`
      self$`confirmed` <- CatalogueMatchDTOObject$`confirmed`
      self
    }
  )
)
