# SQE API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CharacterShapeDTO
#'
#' @description CharacterShapeDTO Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  integer 
#'
#' @field character  character 
#'
#' @field polygon  character 
#'
#' @field imageURL  character 
#'
#' @field rotation  numeric [optional]
#'
#' @field attributes  list( character ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CharacterShapeDTO <- R6::R6Class(
  'CharacterShapeDTO',
  public = list(
    `id` = NULL,
    `character` = NULL,
    `polygon` = NULL,
    `imageURL` = NULL,
    `rotation` = NULL,
    `attributes` = NULL,
    initialize = function(
        `id`, `character`, `polygon`, `imageURL`, `attributes`, `rotation`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`character`)) {
        stopifnot(is.character(`character`), length(`character`) == 1)
        self$`character` <- `character`
      }
      if (!missing(`polygon`)) {
        stopifnot(is.character(`polygon`), length(`polygon`) == 1)
        self$`polygon` <- `polygon`
      }
      if (!missing(`imageURL`)) {
        stopifnot(is.character(`imageURL`), length(`imageURL`) == 1)
        self$`imageURL` <- `imageURL`
      }
      if (!missing(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(is.character(x)))
        self$`attributes` <- `attributes`
      }
      if (!is.null(`rotation`)) {
        stopifnot(is.numeric(`rotation`), length(`rotation`) == 1)
        self$`rotation` <- `rotation`
      }
    },
    toJSON = function() {
      CharacterShapeDTOObject <- list()
      if (!is.null(self$`id`)) {
        CharacterShapeDTOObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`character`)) {
        CharacterShapeDTOObject[['character']] <-
          self$`character`
      }
      if (!is.null(self$`polygon`)) {
        CharacterShapeDTOObject[['polygon']] <-
          self$`polygon`
      }
      if (!is.null(self$`imageURL`)) {
        CharacterShapeDTOObject[['imageURL']] <-
          self$`imageURL`
      }
      if (!is.null(self$`rotation`)) {
        CharacterShapeDTOObject[['rotation']] <-
          self$`rotation`
      }
      if (!is.null(self$`attributes`)) {
        CharacterShapeDTOObject[['attributes']] <-
          self$`attributes`
      }

      CharacterShapeDTOObject
    },
    fromJSON = function(CharacterShapeDTOJson) {
      CharacterShapeDTOObject <- jsonlite::fromJSON(CharacterShapeDTOJson)
      if (!is.null(CharacterShapeDTOObject$`id`)) {
        self$`id` <- CharacterShapeDTOObject$`id`
      }
      if (!is.null(CharacterShapeDTOObject$`character`)) {
        self$`character` <- CharacterShapeDTOObject$`character`
      }
      if (!is.null(CharacterShapeDTOObject$`polygon`)) {
        self$`polygon` <- CharacterShapeDTOObject$`polygon`
      }
      if (!is.null(CharacterShapeDTOObject$`imageURL`)) {
        self$`imageURL` <- CharacterShapeDTOObject$`imageURL`
      }
      if (!is.null(CharacterShapeDTOObject$`rotation`)) {
        self$`rotation` <- CharacterShapeDTOObject$`rotation`
      }
      if (!is.null(CharacterShapeDTOObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(CharacterShapeDTOObject$`attributes`, "array[character]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`character`)) {
        sprintf(
        '"character":
          "%s"
                ',
        self$`character`
        )},
        if (!is.null(self$`polygon`)) {
        sprintf(
        '"polygon":
          "%s"
                ',
        self$`polygon`
        )},
        if (!is.null(self$`imageURL`)) {
        sprintf(
        '"imageURL":
          "%s"
                ',
        self$`imageURL`
        )},
        if (!is.null(self$`rotation`)) {
        sprintf(
        '"rotation":
          %d
                ',
        self$`rotation`
        )},
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
           [%s]
        ',
        paste(unlist(lapply(self$`attributes`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CharacterShapeDTOJson) {
      CharacterShapeDTOObject <- jsonlite::fromJSON(CharacterShapeDTOJson)
      self$`id` <- CharacterShapeDTOObject$`id`
      self$`character` <- CharacterShapeDTOObject$`character`
      self$`polygon` <- CharacterShapeDTOObject$`polygon`
      self$`imageURL` <- CharacterShapeDTOObject$`imageURL`
      self$`rotation` <- CharacterShapeDTOObject$`rotation`
      self$`attributes` <- ApiClient$new()$deserializeObj(CharacterShapeDTOObject$`attributes`, "array[character]", loadNamespace("openapi"))
      self
    }
  )
)

