# SQE API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CommentaryCreateDTO
#'
#' @description CommentaryCreateDTO Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field commentary  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CommentaryCreateDTO <- R6::R6Class(
  'CommentaryCreateDTO',
  public = list(
    `commentary` = NULL,
    initialize = function(
        `commentary`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`commentary`)) {
        stopifnot(is.character(`commentary`), length(`commentary`) == 1)
        self$`commentary` <- `commentary`
      }
    },
    toJSON = function() {
      CommentaryCreateDTOObject <- list()
      if (!is.null(self$`commentary`)) {
        CommentaryCreateDTOObject[['commentary']] <-
          self$`commentary`
      }

      CommentaryCreateDTOObject
    },
    fromJSON = function(CommentaryCreateDTOJson) {
      CommentaryCreateDTOObject <- jsonlite::fromJSON(CommentaryCreateDTOJson)
      if (!is.null(CommentaryCreateDTOObject$`commentary`)) {
        self$`commentary` <- CommentaryCreateDTOObject$`commentary`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`commentary`)) {
        sprintf(
        '"commentary":
          "%s"
                ',
        self$`commentary`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CommentaryCreateDTOJson) {
      CommentaryCreateDTOObject <- jsonlite::fromJSON(CommentaryCreateDTOJson)
      self$`commentary` <- CommentaryCreateDTOObject$`commentary`
      self
    }
  )
)

