# SQE API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title EditionListDTO
#' @description EditionListDTO Class
#' @format An \code{R6Class} generator object
#' @field editions  list( \link{array[EditionDTO]} ) 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EditionListDTO <- R6::R6Class(
  'EditionListDTO',
  public = list(
    `editions` = NULL,
    initialize = function(`editions`, ...){
      local.optional.var <- list(...)
      if (!missing(`editions`)) {
        stopifnot(is.vector(`editions`), length(`editions`) != 0)
        sapply(`editions`, function(x) stopifnot(R6::is.R6(x)))
        self$`editions` <- `editions`
      }
    },
    toJSON = function() {
      EditionListDTOObject <- list()
      if (!is.null(self$`editions`)) {
        EditionListDTOObject[['editions']] <-
          lapply(self$`editions`, function(x) x$toJSON())
      }

      EditionListDTOObject
    },
    fromJSON = function(EditionListDTOJson) {
      EditionListDTOObject <- jsonlite::fromJSON(EditionListDTOJson)
      if (!is.null(EditionListDTOObject$`editions`)) {
        self$`editions` <- ApiClient$new()$deserializeObj(EditionListDTOObject$`editions`, "array[array[EditionDTO]]", loadNamespace("qumranica_api_connector"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`editions`)) {
        sprintf(
        '"editions":
        [%s]
',
        paste(sapply(self$`editions`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(EditionListDTOJson) {
      EditionListDTOObject <- jsonlite::fromJSON(EditionListDTOJson)
      self$`editions` <- ApiClient$new()$deserializeObj(EditionListDTOObject$`editions`, "array[array[EditionDTO]]", loadNamespace("qumranica_api_connector"))
      self
    }
  )
)
