# SQE API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title EditionCopyDTO
#' @description EditionCopyDTO Class
#' @format An \code{R6Class} generator object
#' @field name  character [optional]
#'
#' @field copyrightHolder  character [optional]
#'
#' @field collaborators  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EditionCopyDTO <- R6::R6Class(
  'EditionCopyDTO',
  public = list(
    `name` = NULL,
    `copyrightHolder` = NULL,
    `collaborators` = NULL,
    initialize = function(`name`=NULL, `copyrightHolder`=NULL, `collaborators`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`copyrightHolder`)) {
        stopifnot(is.character(`copyrightHolder`), length(`copyrightHolder`) == 1)
        self$`copyrightHolder` <- `copyrightHolder`
      }
      if (!is.null(`collaborators`)) {
        stopifnot(is.character(`collaborators`), length(`collaborators`) == 1)
        self$`collaborators` <- `collaborators`
      }
    },
    toJSON = function() {
      EditionCopyDTOObject <- list()
      if (!is.null(self$`name`)) {
        EditionCopyDTOObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`copyrightHolder`)) {
        EditionCopyDTOObject[['copyrightHolder']] <-
          self$`copyrightHolder`
      }
      if (!is.null(self$`collaborators`)) {
        EditionCopyDTOObject[['collaborators']] <-
          self$`collaborators`
      }

      EditionCopyDTOObject
    },
    fromJSON = function(EditionCopyDTOJson) {
      EditionCopyDTOObject <- jsonlite::fromJSON(EditionCopyDTOJson)
      if (!is.null(EditionCopyDTOObject$`name`)) {
        self$`name` <- EditionCopyDTOObject$`name`
      }
      if (!is.null(EditionCopyDTOObject$`copyrightHolder`)) {
        self$`copyrightHolder` <- EditionCopyDTOObject$`copyrightHolder`
      }
      if (!is.null(EditionCopyDTOObject$`collaborators`)) {
        self$`collaborators` <- EditionCopyDTOObject$`collaborators`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`copyrightHolder`)) {
        sprintf(
        '"copyrightHolder":
          "%s"
                ',
        self$`copyrightHolder`
        )},
        if (!is.null(self$`collaborators`)) {
        sprintf(
        '"collaborators":
          "%s"
                ',
        self$`collaborators`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(EditionCopyDTOJson) {
      EditionCopyDTOObject <- jsonlite::fromJSON(EditionCopyDTOJson)
      self$`name` <- EditionCopyDTOObject$`name`
      self$`copyrightHolder` <- EditionCopyDTOObject$`copyrightHolder`
      self$`collaborators` <- EditionCopyDTOObject$`collaborators`
      self
    }
  )
)
