# SQE API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ImagedObjectTextFragmentMatchListDTO
#' @description ImagedObjectTextFragmentMatchListDTO Class
#' @format An \code{R6Class} generator object
#' @field matches  list( \link{ImagedObjectTextFragmentMatchDTO} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ImagedObjectTextFragmentMatchListDTO <- R6::R6Class(
  'ImagedObjectTextFragmentMatchListDTO',
  public = list(
    `matches` = NULL,
    initialize = function(`matches`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`matches`)) {
        stopifnot(is.vector(`matches`), length(`matches`) != 0)
        sapply(`matches`, function(x) stopifnot(R6::is.R6(x)))
        self$`matches` <- `matches`
      }
    },
    toJSON = function() {
      ImagedObjectTextFragmentMatchListDTOObject <- list()
      if (!is.null(self$`matches`)) {
        ImagedObjectTextFragmentMatchListDTOObject[['matches']] <-
          lapply(self$`matches`, function(x) x$toJSON())
      }

      ImagedObjectTextFragmentMatchListDTOObject
    },
    fromJSON = function(ImagedObjectTextFragmentMatchListDTOJson) {
      ImagedObjectTextFragmentMatchListDTOObject <- jsonlite::fromJSON(ImagedObjectTextFragmentMatchListDTOJson)
      if (!is.null(ImagedObjectTextFragmentMatchListDTOObject$`matches`)) {
        self$`matches` <- ApiClient$new()$deserializeObj(ImagedObjectTextFragmentMatchListDTOObject$`matches`, "array[ImagedObjectTextFragmentMatchDTO]", loadNamespace("qumranica_api_connector"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`matches`)) {
        sprintf(
        '"matches":
        [%s]
',
        paste(sapply(self$`matches`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ImagedObjectTextFragmentMatchListDTOJson) {
      ImagedObjectTextFragmentMatchListDTOObject <- jsonlite::fromJSON(ImagedObjectTextFragmentMatchListDTOJson)
      self$`matches` <- ApiClient$new()$deserializeObj(ImagedObjectTextFragmentMatchListDTOObject$`matches`, "array[ImagedObjectTextFragmentMatchDTO]", loadNamespace("qumranica_api_connector"))
      self
    }
  )
)
