# SQE API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title NewUserRequestDTO
#'
#' @description NewUserRequestDTO Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field email  character 
#'
#' @field password  character 
#'
#' @field organization  character [optional]
#'
#' @field forename  character [optional]
#'
#' @field surname  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NewUserRequestDTO <- R6::R6Class(
  'NewUserRequestDTO',
  public = list(
    `email` = NULL,
    `password` = NULL,
    `organization` = NULL,
    `forename` = NULL,
    `surname` = NULL,
    initialize = function(
        `email`, `password`, `organization`=NULL, `forename`=NULL, `surname`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
      if (!missing(`password`)) {
        stopifnot(is.character(`password`), length(`password`) == 1)
        self$`password` <- `password`
      }
      if (!is.null(`organization`)) {
        stopifnot(is.character(`organization`), length(`organization`) == 1)
        self$`organization` <- `organization`
      }
      if (!is.null(`forename`)) {
        stopifnot(is.character(`forename`), length(`forename`) == 1)
        self$`forename` <- `forename`
      }
      if (!is.null(`surname`)) {
        stopifnot(is.character(`surname`), length(`surname`) == 1)
        self$`surname` <- `surname`
      }
    },
    toJSON = function() {
      NewUserRequestDTOObject <- list()
      if (!is.null(self$`email`)) {
        NewUserRequestDTOObject[['email']] <-
          self$`email`
      }
      if (!is.null(self$`password`)) {
        NewUserRequestDTOObject[['password']] <-
          self$`password`
      }
      if (!is.null(self$`organization`)) {
        NewUserRequestDTOObject[['organization']] <-
          self$`organization`
      }
      if (!is.null(self$`forename`)) {
        NewUserRequestDTOObject[['forename']] <-
          self$`forename`
      }
      if (!is.null(self$`surname`)) {
        NewUserRequestDTOObject[['surname']] <-
          self$`surname`
      }

      NewUserRequestDTOObject
    },
    fromJSON = function(NewUserRequestDTOJson) {
      NewUserRequestDTOObject <- jsonlite::fromJSON(NewUserRequestDTOJson)
      if (!is.null(NewUserRequestDTOObject$`email`)) {
        self$`email` <- NewUserRequestDTOObject$`email`
      }
      if (!is.null(NewUserRequestDTOObject$`password`)) {
        self$`password` <- NewUserRequestDTOObject$`password`
      }
      if (!is.null(NewUserRequestDTOObject$`organization`)) {
        self$`organization` <- NewUserRequestDTOObject$`organization`
      }
      if (!is.null(NewUserRequestDTOObject$`forename`)) {
        self$`forename` <- NewUserRequestDTOObject$`forename`
      }
      if (!is.null(NewUserRequestDTOObject$`surname`)) {
        self$`surname` <- NewUserRequestDTOObject$`surname`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`email`)) {
        sprintf(
        '"email":
          "%s"
                ',
        self$`email`
        )},
        if (!is.null(self$`password`)) {
        sprintf(
        '"password":
          "%s"
                ',
        self$`password`
        )},
        if (!is.null(self$`organization`)) {
        sprintf(
        '"organization":
          "%s"
                ',
        self$`organization`
        )},
        if (!is.null(self$`forename`)) {
        sprintf(
        '"forename":
          "%s"
                ',
        self$`forename`
        )},
        if (!is.null(self$`surname`)) {
        sprintf(
        '"surname":
          "%s"
                ',
        self$`surname`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(NewUserRequestDTOJson) {
      NewUserRequestDTOObject <- jsonlite::fromJSON(NewUserRequestDTOJson)
      self$`email` <- NewUserRequestDTOObject$`email`
      self$`password` <- NewUserRequestDTOObject$`password`
      self$`organization` <- NewUserRequestDTOObject$`organization`
      self$`forename` <- NewUserRequestDTOObject$`forename`
      self$`surname` <- NewUserRequestDTOObject$`surname`
      self
    }
  )
)

