# SQE API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ScriptLineDTO
#'
#' @description ScriptLineDTO Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field lineName  character 
#'
#' @field lineId  integer 
#'
#' @field artefacts  list( \link{ScriptArtefactCharactersDTO} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ScriptLineDTO <- R6::R6Class(
  'ScriptLineDTO',
  public = list(
    `lineName` = NULL,
    `lineId` = NULL,
    `artefacts` = NULL,
    initialize = function(
        `lineName`, `lineId`, `artefacts`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`lineName`)) {
        stopifnot(is.character(`lineName`), length(`lineName`) == 1)
        self$`lineName` <- `lineName`
      }
      if (!missing(`lineId`)) {
        stopifnot(is.numeric(`lineId`), length(`lineId`) == 1)
        self$`lineId` <- `lineId`
      }
      if (!missing(`artefacts`)) {
        stopifnot(is.vector(`artefacts`), length(`artefacts`) != 0)
        sapply(`artefacts`, function(x) stopifnot(R6::is.R6(x)))
        self$`artefacts` <- `artefacts`
      }
    },
    toJSON = function() {
      ScriptLineDTOObject <- list()
      if (!is.null(self$`lineName`)) {
        ScriptLineDTOObject[['lineName']] <-
          self$`lineName`
      }
      if (!is.null(self$`lineId`)) {
        ScriptLineDTOObject[['lineId']] <-
          self$`lineId`
      }
      if (!is.null(self$`artefacts`)) {
        ScriptLineDTOObject[['artefacts']] <-
          lapply(self$`artefacts`, function(x) x$toJSON())
      }

      ScriptLineDTOObject
    },
    fromJSON = function(ScriptLineDTOJson) {
      ScriptLineDTOObject <- jsonlite::fromJSON(ScriptLineDTOJson)
      if (!is.null(ScriptLineDTOObject$`lineName`)) {
        self$`lineName` <- ScriptLineDTOObject$`lineName`
      }
      if (!is.null(ScriptLineDTOObject$`lineId`)) {
        self$`lineId` <- ScriptLineDTOObject$`lineId`
      }
      if (!is.null(ScriptLineDTOObject$`artefacts`)) {
        self$`artefacts` <- ApiClient$new()$deserializeObj(ScriptLineDTOObject$`artefacts`, "array[ScriptArtefactCharactersDTO]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`lineName`)) {
        sprintf(
        '"lineName":
          "%s"
                ',
        self$`lineName`
        )},
        if (!is.null(self$`lineId`)) {
        sprintf(
        '"lineId":
          %d
                ',
        self$`lineId`
        )},
        if (!is.null(self$`artefacts`)) {
        sprintf(
        '"artefacts":
        [%s]
',
        paste(sapply(self$`artefacts`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ScriptLineDTOJson) {
      ScriptLineDTOObject <- jsonlite::fromJSON(ScriptLineDTOJson)
      self$`lineName` <- ScriptLineDTOObject$`lineName`
      self$`lineId` <- ScriptLineDTOObject$`lineId`
      self$`artefacts` <- ApiClient$new()$deserializeObj(ScriptLineDTOObject$`artefacts`, "array[ScriptArtefactCharactersDTO]", loadNamespace("openapi"))
      self
    }
  )
)

