# SQE API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SignInterpretationListDTO
#' @description SignInterpretationListDTO Class
#' @format An \code{R6Class} generator object
#' @field signInterpretations  list( \link{SignInterpretationDTO} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SignInterpretationListDTO <- R6::R6Class(
  'SignInterpretationListDTO',
  public = list(
    `signInterpretations` = NULL,
    initialize = function(`signInterpretations`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`signInterpretations`)) {
        stopifnot(is.vector(`signInterpretations`), length(`signInterpretations`) != 0)
        sapply(`signInterpretations`, function(x) stopifnot(R6::is.R6(x)))
        self$`signInterpretations` <- `signInterpretations`
      }
    },
    toJSON = function() {
      SignInterpretationListDTOObject <- list()
      if (!is.null(self$`signInterpretations`)) {
        SignInterpretationListDTOObject[['signInterpretations']] <-
          lapply(self$`signInterpretations`, function(x) x$toJSON())
      }

      SignInterpretationListDTOObject
    },
    fromJSON = function(SignInterpretationListDTOJson) {
      SignInterpretationListDTOObject <- jsonlite::fromJSON(SignInterpretationListDTOJson)
      if (!is.null(SignInterpretationListDTOObject$`signInterpretations`)) {
        self$`signInterpretations` <- ApiClient$new()$deserializeObj(SignInterpretationListDTOObject$`signInterpretations`, "array[SignInterpretationDTO]", loadNamespace("qumranica_api_connector"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`signInterpretations`)) {
        sprintf(
        '"signInterpretations":
        [%s]
',
        paste(sapply(self$`signInterpretations`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SignInterpretationListDTOJson) {
      SignInterpretationListDTOObject <- jsonlite::fromJSON(SignInterpretationListDTOJson)
      self$`signInterpretations` <- ApiClient$new()$deserializeObj(SignInterpretationListDTOObject$`signInterpretations`, "array[SignInterpretationDTO]", loadNamespace("qumranica_api_connector"))
      self
    }
  )
)
