# SQE API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SignDTO
#' @description SignDTO Class
#' @format An \code{R6Class} generator object
#' @field signInterpretations  list( \link{SignInterpretationDTO} ) 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SignDTO <- R6::R6Class(
  'SignDTO',
  public = list(
    `signInterpretations` = NULL,
    initialize = function(`signInterpretations`, ...){
      local.optional.var <- list(...)
      if (!missing(`signInterpretations`)) {
        stopifnot(is.vector(`signInterpretations`), length(`signInterpretations`) != 0)
        sapply(`signInterpretations`, function(x) stopifnot(R6::is.R6(x)))
        self$`signInterpretations` <- `signInterpretations`
      }
    },
    toJSON = function() {
      SignDTOObject <- list()
      if (!is.null(self$`signInterpretations`)) {
        SignDTOObject[['signInterpretations']] <-
          lapply(self$`signInterpretations`, function(x) x$toJSON())
      }

      SignDTOObject
    },
    fromJSON = function(SignDTOJson) {
      SignDTOObject <- jsonlite::fromJSON(SignDTOJson)
      if (!is.null(SignDTOObject$`signInterpretations`)) {
        self$`signInterpretations` <- ApiClient$new()$deserializeObj(SignDTOObject$`signInterpretations`, "array[SignInterpretationDTO]", loadNamespace("qumranicaApiConnector"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`signInterpretations`)) {
        sprintf(
        '"signInterpretations":
        [%s]
',
        paste(sapply(self$`signInterpretations`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SignDTOJson) {
      SignDTOObject <- jsonlite::fromJSON(SignDTOJson)
      self$`signInterpretations` <- ApiClient$new()$deserializeObj(SignDTOObject$`signInterpretations`, "array[SignInterpretationDTO]", loadNamespace("qumranicaApiConnector"))
      self
    }
  )
)
