# SQE API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TextFragmentDataListDTO
#' @description TextFragmentDataListDTO Class
#' @format An \code{R6Class} generator object
#' @field textFragments  list( \link{TextFragmentDataDTO} ) 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TextFragmentDataListDTO <- R6::R6Class(
  'TextFragmentDataListDTO',
  public = list(
    `textFragments` = NULL,
    initialize = function(`textFragments`, ...){
      local.optional.var <- list(...)
      if (!missing(`textFragments`)) {
        stopifnot(is.vector(`textFragments`), length(`textFragments`) != 0)
        sapply(`textFragments`, function(x) stopifnot(R6::is.R6(x)))
        self$`textFragments` <- `textFragments`
      }
    },
    toJSON = function() {
      TextFragmentDataListDTOObject <- list()
      if (!is.null(self$`textFragments`)) {
        TextFragmentDataListDTOObject[['textFragments']] <-
          lapply(self$`textFragments`, function(x) x$toJSON())
      }

      TextFragmentDataListDTOObject
    },
    fromJSON = function(TextFragmentDataListDTOJson) {
      TextFragmentDataListDTOObject <- jsonlite::fromJSON(TextFragmentDataListDTOJson)
      if (!is.null(TextFragmentDataListDTOObject$`textFragments`)) {
        self$`textFragments` <- ApiClient$new()$deserializeObj(TextFragmentDataListDTOObject$`textFragments`, "array[TextFragmentDataDTO]", loadNamespace("qumranica_api_connector"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`textFragments`)) {
        sprintf(
        '"textFragments":
        [%s]
',
        paste(sapply(self$`textFragments`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TextFragmentDataListDTOJson) {
      TextFragmentDataListDTOObject <- jsonlite::fromJSON(TextFragmentDataListDTOJson)
      self$`textFragments` <- ApiClient$new()$deserializeObj(TextFragmentDataListDTOObject$`textFragments`, "array[TextFragmentDataDTO]", loadNamespace("qumranica_api_connector"))
      self
    }
  )
)
