# SQE API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TextEditionDTO
#' @description TextEditionDTO Class
#' @format An \code{R6Class} generator object
#' @field manuscriptId  integer 
#'
#' @field editionName  character 
#'
#' @field editorId  integer 
#'
#' @field licence  character 
#'
#' @field editors  named list( \link{EditorDTO} ) 
#'
#' @field textFragments  list( \link{TextFragmentDTO} ) 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TextEditionDTO <- R6::R6Class(
  'TextEditionDTO',
  public = list(
    `manuscriptId` = NULL,
    `editionName` = NULL,
    `editorId` = NULL,
    `licence` = NULL,
    `editors` = NULL,
    `textFragments` = NULL,
    initialize = function(`manuscriptId`, `editionName`, `editorId`, `licence`, `editors`, `textFragments`, ...){
      local.optional.var <- list(...)
      if (!missing(`manuscriptId`)) {
        stopifnot(is.numeric(`manuscriptId`), length(`manuscriptId`) == 1)
        self$`manuscriptId` <- `manuscriptId`
      }
      if (!missing(`editionName`)) {
        stopifnot(is.character(`editionName`), length(`editionName`) == 1)
        self$`editionName` <- `editionName`
      }
      if (!missing(`editorId`)) {
        stopifnot(is.numeric(`editorId`), length(`editorId`) == 1)
        self$`editorId` <- `editorId`
      }
      if (!missing(`licence`)) {
        stopifnot(is.character(`licence`), length(`licence`) == 1)
        self$`licence` <- `licence`
      }
      if (!missing(`editors`)) {
        stopifnot(is.vector(`editors`), length(`editors`) != 0)
        sapply(`editors`, function(x) stopifnot(R6::is.R6(x)))
        self$`editors` <- `editors`
      }
      if (!missing(`textFragments`)) {
        stopifnot(is.vector(`textFragments`), length(`textFragments`) != 0)
        sapply(`textFragments`, function(x) stopifnot(R6::is.R6(x)))
        self$`textFragments` <- `textFragments`
      }
    },
    toJSON = function() {
      TextEditionDTOObject <- list()
      if (!is.null(self$`manuscriptId`)) {
        TextEditionDTOObject[['manuscriptId']] <-
          self$`manuscriptId`
      }
      if (!is.null(self$`editionName`)) {
        TextEditionDTOObject[['editionName']] <-
          self$`editionName`
      }
      if (!is.null(self$`editorId`)) {
        TextEditionDTOObject[['editorId']] <-
          self$`editorId`
      }
      if (!is.null(self$`licence`)) {
        TextEditionDTOObject[['licence']] <-
          self$`licence`
      }
      if (!is.null(self$`editors`)) {
        TextEditionDTOObject[['editors']] <-
          lapply(self$`editors`, function(x) x$toJSON())
      }
      if (!is.null(self$`textFragments`)) {
        TextEditionDTOObject[['textFragments']] <-
          lapply(self$`textFragments`, function(x) x$toJSON())
      }

      TextEditionDTOObject
    },
    fromJSON = function(TextEditionDTOJson) {
      TextEditionDTOObject <- jsonlite::fromJSON(TextEditionDTOJson)
      if (!is.null(TextEditionDTOObject$`manuscriptId`)) {
        self$`manuscriptId` <- TextEditionDTOObject$`manuscriptId`
      }
      if (!is.null(TextEditionDTOObject$`editionName`)) {
        self$`editionName` <- TextEditionDTOObject$`editionName`
      }
      if (!is.null(TextEditionDTOObject$`editorId`)) {
        self$`editorId` <- TextEditionDTOObject$`editorId`
      }
      if (!is.null(TextEditionDTOObject$`licence`)) {
        self$`licence` <- TextEditionDTOObject$`licence`
      }
      if (!is.null(TextEditionDTOObject$`editors`)) {
        self$`editors` <- ApiClient$new()$deserializeObj(TextEditionDTOObject$`editors`, "map(EditorDTO)", loadNamespace("qumranica_api_connector"))
      }
      if (!is.null(TextEditionDTOObject$`textFragments`)) {
        self$`textFragments` <- ApiClient$new()$deserializeObj(TextEditionDTOObject$`textFragments`, "array[TextFragmentDTO]", loadNamespace("qumranica_api_connector"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`manuscriptId`)) {
        sprintf(
        '"manuscriptId":
          %d
                ',
        self$`manuscriptId`
        )},
        if (!is.null(self$`editionName`)) {
        sprintf(
        '"editionName":
          "%s"
                ',
        self$`editionName`
        )},
        if (!is.null(self$`editorId`)) {
        sprintf(
        '"editorId":
          %d
                ',
        self$`editorId`
        )},
        if (!is.null(self$`licence`)) {
        sprintf(
        '"licence":
          "%s"
                ',
        self$`licence`
        )},
        if (!is.null(self$`editors`)) {
        sprintf(
        '"editors":
        %s
',
        jsonlite::toJSON(lapply(self$`editors`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`textFragments`)) {
        sprintf(
        '"textFragments":
        [%s]
',
        paste(sapply(self$`textFragments`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TextEditionDTOJson) {
      TextEditionDTOObject <- jsonlite::fromJSON(TextEditionDTOJson)
      self$`manuscriptId` <- TextEditionDTOObject$`manuscriptId`
      self$`editionName` <- TextEditionDTOObject$`editionName`
      self$`editorId` <- TextEditionDTOObject$`editorId`
      self$`licence` <- TextEditionDTOObject$`licence`
      self$`editors` <- ApiClient$new()$deserializeObj(TextEditionDTOObject$`editors`, "map(EditorDTO)", loadNamespace("qumranica_api_connector"))
      self$`textFragments` <- ApiClient$new()$deserializeObj(TextEditionDTOObject$`textFragments`, "array[TextFragmentDTO]", loadNamespace("qumranica_api_connector"))
      self
    }
  )
)
