# SQE API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UpdatedArtefactPlacementDTO
#'
#' @description UpdatedArtefactPlacementDTO Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field placementEditorId  integer 
#'
#' @field artefactId  integer 
#'
#' @field isPlaced  character 
#'
#' @field placement  \link{PlacementDTO} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UpdatedArtefactPlacementDTO <- R6::R6Class(
  'UpdatedArtefactPlacementDTO',
  public = list(
    `placementEditorId` = NULL,
    `artefactId` = NULL,
    `isPlaced` = NULL,
    `placement` = NULL,
    initialize = function(
        `placementEditorId`, `artefactId`, `isPlaced`, `placement`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`placementEditorId`)) {
        stopifnot(is.numeric(`placementEditorId`), length(`placementEditorId`) == 1)
        self$`placementEditorId` <- `placementEditorId`
      }
      if (!missing(`artefactId`)) {
        stopifnot(is.numeric(`artefactId`), length(`artefactId`) == 1)
        self$`artefactId` <- `artefactId`
      }
      if (!missing(`isPlaced`)) {
        self$`isPlaced` <- `isPlaced`
      }
      if (!is.null(`placement`)) {
        stopifnot(R6::is.R6(`placement`))
        self$`placement` <- `placement`
      }
    },
    toJSON = function() {
      UpdatedArtefactPlacementDTOObject <- list()
      if (!is.null(self$`placementEditorId`)) {
        UpdatedArtefactPlacementDTOObject[['placementEditorId']] <-
          self$`placementEditorId`
      }
      if (!is.null(self$`artefactId`)) {
        UpdatedArtefactPlacementDTOObject[['artefactId']] <-
          self$`artefactId`
      }
      if (!is.null(self$`isPlaced`)) {
        UpdatedArtefactPlacementDTOObject[['isPlaced']] <-
          self$`isPlaced`
      }
      if (!is.null(self$`placement`)) {
        UpdatedArtefactPlacementDTOObject[['placement']] <-
          self$`placement`$toJSON()
      }

      UpdatedArtefactPlacementDTOObject
    },
    fromJSON = function(UpdatedArtefactPlacementDTOJson) {
      UpdatedArtefactPlacementDTOObject <- jsonlite::fromJSON(UpdatedArtefactPlacementDTOJson)
      if (!is.null(UpdatedArtefactPlacementDTOObject$`placementEditorId`)) {
        self$`placementEditorId` <- UpdatedArtefactPlacementDTOObject$`placementEditorId`
      }
      if (!is.null(UpdatedArtefactPlacementDTOObject$`artefactId`)) {
        self$`artefactId` <- UpdatedArtefactPlacementDTOObject$`artefactId`
      }
      if (!is.null(UpdatedArtefactPlacementDTOObject$`isPlaced`)) {
        self$`isPlaced` <- UpdatedArtefactPlacementDTOObject$`isPlaced`
      }
      if (!is.null(UpdatedArtefactPlacementDTOObject$`placement`)) {
        placementObject <- PlacementDTO$new()
        placementObject$fromJSON(jsonlite::toJSON(UpdatedArtefactPlacementDTOObject$placement, auto_unbox = TRUE, digits = NA))
        self$`placement` <- placementObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`placementEditorId`)) {
        sprintf(
        '"placementEditorId":
          %d
                ',
        self$`placementEditorId`
        )},
        if (!is.null(self$`artefactId`)) {
        sprintf(
        '"artefactId":
          %d
                ',
        self$`artefactId`
        )},
        if (!is.null(self$`isPlaced`)) {
        sprintf(
        '"isPlaced":
          "%s"
                ',
        self$`isPlaced`
        )},
        if (!is.null(self$`placement`)) {
        sprintf(
        '"placement":
        %s
        ',
        jsonlite::toJSON(self$`placement`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(UpdatedArtefactPlacementDTOJson) {
      UpdatedArtefactPlacementDTOObject <- jsonlite::fromJSON(UpdatedArtefactPlacementDTOJson)
      self$`placementEditorId` <- UpdatedArtefactPlacementDTOObject$`placementEditorId`
      self$`artefactId` <- UpdatedArtefactPlacementDTOObject$`artefactId`
      self$`isPlaced` <- UpdatedArtefactPlacementDTOObject$`isPlaced`
      self$`placement` <- PlacementDTO$new()$fromJSON(jsonlite::toJSON(UpdatedArtefactPlacementDTOObject$placement, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

