/* tslint:disable */
/* eslint-disable */
/**
 * SQE API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    WktPolygonDTO,
    WktPolygonDTOFromJSON,
    WktPolygonDTOToJSON,
} from '../models';

export interface V1UtilsRepairWktPolygonPostRequest {
    wktPolygonDTO?: WktPolygonDTO;
}

/**
 * 
 */
export class UtilApi extends runtime.BaseAPI {

    /**
     * Checks a WKT polygon to ensure validity. If the polygon is invalid,  it attempts to construct a valid polygon that matches the original  as closely as possible.
     */
    async v1UtilsRepairWktPolygonPostRaw(requestParameters: V1UtilsRepairWktPolygonPostRequest): Promise<runtime.ApiResponse<WktPolygonDTO>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/v1/utils/repair-wkt-polygon`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WktPolygonDTOToJSON(requestParameters.wktPolygonDTO),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => WktPolygonDTOFromJSON(jsonValue));
    }

    /**
     * Checks a WKT polygon to ensure validity. If the polygon is invalid,  it attempts to construct a valid polygon that matches the original  as closely as possible.
     */
    async v1UtilsRepairWktPolygonPost(requestParameters: V1UtilsRepairWktPolygonPostRequest): Promise<WktPolygonDTO> {
        const response = await this.v1UtilsRepairWktPolygonPostRaw(requestParameters);
        return await response.value();
    }

}
