# coding: utf-8

"""
    SQE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.text_edition_dto import TextEditionDTO  # noqa: E501
from openapi_client.rest import ApiException

class TestTextEditionDTO(unittest.TestCase):
    """TextEditionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TextEditionDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.text_edition_dto.TextEditionDTO()  # noqa: E501
        if include_optional :
            return TextEditionDTO(
                manuscript_id = 56, 
                edition_name = '0', 
                editor_id = 56, 
                licence = '0', 
                editors = {
                    'key' : openapi_client.models.editor_dto.EditorDTO(
                        email = '0', 
                        forename = '0', 
                        surname = '0', 
                        organization = '0', )
                    }, 
                text_fragments = [
                    openapi_client.models.text_fragment_dto.TextFragmentDTO(
                        text_fragment_id = 56, 
                        text_fragment_name = '0', 
                        editor_id = 56, 
                        lines = [
                            openapi_client.models.line_dto.LineDTO(
                                line_id = 56, 
                                line_name = '0', 
                                editor_id = 56, 
                                signs = [
                                    openapi_client.models.sign_dto.SignDTO(
                                        sign_interpretations = [
                                            openapi_client.models.sign_interpretation_dto.SignInterpretationDTO(
                                                sign_interpretation_id = 56, 
                                                next_sign_interpretations = [
                                                    openapi_client.models.next_sign_interpretation_dto.NextSignInterpretationDTO(
                                                        next_sign_interpretation_id = 56, 
                                                        creator_id = 56, 
                                                        editor_id = 56, )
                                                    ], 
                                                attributes = [
                                                    openapi_client.models.interpretation_attribute_dto.InterpretationAttributeDTO(
                                                        interpretation_attribute_id = 56, 
                                                        attribute_string = '0', 
                                                        attribute_value_string = '0', 
                                                        creator_id = 56, 
                                                        editor_id = 56, 
                                                        commentary = null, 
                                                        sequence = 56, 
                                                        attribute_id = 56, 
                                                        attribute_value_id = 56, )
                                                    ], 
                                                rois = [
                                                    openapi_client.models.interpretation_roi_dto.InterpretationRoiDTO(
                                                        creator_id = 56, 
                                                        editor_id = 56, 
                                                        interpretation_roi_id = 56, 
                                                        artefact_id = 56, 
                                                        sign_interpretation_id = 56, 
                                                        shape = '0', 
                                                        translate = null, 
                                                        stance_rotation = 56, 
                                                        exceptional = True, 
                                                        values_set = True, )
                                                    ], 
                                                commentary = null, 
                                                character = '0', 
                                                is_variant = True, )
                                            ], )
                                    ], )
                            ], )
                    ]
            )
        else :
            return TextEditionDTO(
                manuscript_id = 56,
                edition_name = '0',
                editor_id = 56,
                licence = '0',
                editors = {
                    'key' : openapi_client.models.editor_dto.EditorDTO(
                        email = '0', 
                        forename = '0', 
                        surname = '0', 
                        organization = '0', )
                    },
                text_fragments = [
                    openapi_client.models.text_fragment_dto.TextFragmentDTO(
                        text_fragment_id = 56, 
                        text_fragment_name = '0', 
                        editor_id = 56, 
                        lines = [
                            openapi_client.models.line_dto.LineDTO(
                                line_id = 56, 
                                line_name = '0', 
                                editor_id = 56, 
                                signs = [
                                    openapi_client.models.sign_dto.SignDTO(
                                        sign_interpretations = [
                                            openapi_client.models.sign_interpretation_dto.SignInterpretationDTO(
                                                sign_interpretation_id = 56, 
                                                next_sign_interpretations = [
                                                    openapi_client.models.next_sign_interpretation_dto.NextSignInterpretationDTO(
                                                        next_sign_interpretation_id = 56, 
                                                        creator_id = 56, 
                                                        editor_id = 56, )
                                                    ], 
                                                attributes = [
                                                    openapi_client.models.interpretation_attribute_dto.InterpretationAttributeDTO(
                                                        interpretation_attribute_id = 56, 
                                                        attribute_string = '0', 
                                                        attribute_value_string = '0', 
                                                        creator_id = 56, 
                                                        editor_id = 56, 
                                                        commentary = null, 
                                                        sequence = 56, 
                                                        attribute_id = 56, 
                                                        attribute_value_id = 56, )
                                                    ], 
                                                rois = [
                                                    openapi_client.models.interpretation_roi_dto.InterpretationRoiDTO(
                                                        creator_id = 56, 
                                                        editor_id = 56, 
                                                        interpretation_roi_id = 56, 
                                                        artefact_id = 56, 
                                                        sign_interpretation_id = 56, 
                                                        shape = '0', 
                                                        translate = null, 
                                                        stance_rotation = 56, 
                                                        exceptional = True, 
                                                        values_set = True, )
                                                    ], 
                                                commentary = null, 
                                                character = '0', 
                                                is_variant = True, )
                                            ], )
                                    ], )
                            ], )
                    ],
        )

    def testTextEditionDTO(self):
        """Test TextEditionDTO"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
