# coding: utf-8

"""
    SQE API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.attribute_list_dto import AttributeListDTO  # noqa: E501
from openapi_client.rest import ApiException

class TestAttributeListDTO(unittest.TestCase):
    """AttributeListDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AttributeListDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.attribute_list_dto.AttributeListDTO()  # noqa: E501
        if include_optional :
            return AttributeListDTO(
                attributes = [
                    openapi_client.models.attribute_dto.AttributeDTO(
                        attribute_id = 56, 
                        attribute_name = '0', 
                        values = [
                            openapi_client.models.attribute_value_dto.AttributeValueDTO(
                                creator_id = 56, 
                                editor_id = 56, 
                                id = 56, 
                                value = '0', 
                                description = '0', 
                                css_directives = '0', )
                            ], 
                        creator_id = 56, 
                        editor_id = 56, 
                        description = '0', 
                        editable = True, 
                        removable = True, 
                        repeatable = True, 
                        batch_editable = True, )
                    ]
            )
        else :
            return AttributeListDTO(
                attributes = [
                    openapi_client.models.attribute_dto.AttributeDTO(
                        attribute_id = 56, 
                        attribute_name = '0', 
                        values = [
                            openapi_client.models.attribute_value_dto.AttributeValueDTO(
                                creator_id = 56, 
                                editor_id = 56, 
                                id = 56, 
                                value = '0', 
                                description = '0', 
                                css_directives = '0', )
                            ], 
                        creator_id = 56, 
                        editor_id = 56, 
                        description = '0', 
                        editable = True, 
                        removable = True, 
                        repeatable = True, 
                        batch_editable = True, )
                    ],
        )

    def testAttributeListDTO(self):
        """Test AttributeListDTO"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
